begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
create function pg_temp.cid(text) returns uuid language sql immutable as $$select md5('checkout-test-'||$1)::uuid$$;
insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.cid(u),'00000000-0000-0000-0000-000000000000','authenticated','authenticated',u||'@checkout.example.test','',now(),'{}','{}',now(),now() from unnest(array['owner','outsider','cashier','technician'])u;
insert into organizations(id,name,slug,industry) select pg_temp.cid(v),v,'checkout-test-'||replace(v,'_','-'),v from unnest(array['salon','pet_care','automotive','hospitality'])v;
insert into organizations(id,name,slug,industry) values(pg_temp.cid('other'),'Other','checkout-test-other','salon');
insert into organization_memberships(id,organization_id,user_id,role) select pg_temp.cid('member-'||v),pg_temp.cid(v),pg_temp.cid('owner'),'owner' from unnest(array['salon','pet_care','automotive','hospitality'])v;
insert into organization_memberships(id,organization_id,user_id,role) values(pg_temp.cid('cashier-member'),pg_temp.cid('salon'),pg_temp.cid('cashier'),'cashier'),(pg_temp.cid('tech-member'),pg_temp.cid('salon'),pg_temp.cid('technician'),'technician'),(pg_temp.cid('other-member'),pg_temp.cid('other'),pg_temp.cid('outsider'),'owner');
insert into branches(id,organization_id,name,is_primary) select pg_temp.cid('branch-'||v),pg_temp.cid(v),'Main',true from unnest(array['salon','pet_care','automotive','hospitality','other'])v;
insert into branches(id,organization_id,name,is_primary) values(pg_temp.cid('second-branch'),pg_temp.cid('salon'),'Other',false);
insert into membership_branch_assignments(organization_id,membership_id,branch_id) values(pg_temp.cid('salon'),pg_temp.cid('cashier-member'),pg_temp.cid('branch-salon'));
insert into customers(id,organization_id,full_name) select pg_temp.cid('customer-'||v),pg_temp.cid(v),'Checkout Client' from unnest(array['salon','pet_care','automotive','hospitality','other'])v;
insert into services(id,organization_id,name,duration_minutes,base_price_centavos) select pg_temp.cid('service-'||v),pg_temp.cid(v),'Existing service',30,10000 from unnest(array['salon','pet_care'])v;
insert into inventory_items(id,organization_id,branch_id,name,sku,category,unit,sell_price_centavos,product_purpose) select pg_temp.cid('item-'||v),pg_temp.cid(v),pg_temp.cid('branch-'||v),'Retail bottle','BOTTLE','Care','bottle',2500,'retail' from unnest(array['salon','pet_care','automotive','hospitality','other'])v;
insert into inventory_items(id,organization_id,branch_id,name,unit,sell_price_centavos,product_purpose) values(pg_temp.cid('second-item'),pg_temp.cid('salon'),pg_temp.cid('second-branch'),'Other branch','piece',1000,'retail'),(pg_temp.cid('supply'),pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'Internal supply','ml',500,'internal');
insert into inventory_movements(organization_id,branch_id,inventory_item_id,movement_type,quantity_delta,note) select organization_id,branch_id,id,'opening',10,'Test opening stock' from inventory_items where sku='BOTTLE';
insert into organization_staff_profiles(id,organization_id,full_name) values(pg_temp.cid('unused-staff'),pg_temp.cid('salon'),'Unused staff');
insert into scheduling_resources(id,organization_id,branch_id,name) values(pg_temp.cid('unused-resource'),pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'Unused resource');
insert into hospitality_rooms(id,organization_id,branch_id,name,capacity) values(pg_temp.cid('unused-room'),pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),'Unused room',2),(pg_temp.cid('occupied-room'),pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),'Occupied room',2);
insert into hospitality_stays(id,organization_id,branch_id,room_id,guest_id,room_name_snapshot,guest_name_snapshot,occupants,request_key) values(pg_temp.cid('occupied-stay'),pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),pg_temp.cid('occupied-room'),pg_temp.cid('customer-hospitality'),'Occupied room','Guest',1,pg_temp.cid('occupied-key'));
insert into commerce_promos(id,organization_id,branch_id,name,price_centavos,currency,status,components) values(pg_temp.cid('unused-promo'),pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'Unused promo',10000,'PHP','draft',jsonb_build_array(jsonb_build_object('kind','service','referenceId',pg_temp.cid('service-salon'),'quantity','1','unit','service'),jsonb_build_object('kind','product','referenceId',pg_temp.cid('item-salon'),'quantity','1','unit','bottle')));
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.cid('cashier'),'role','authenticated')::text,true);
set local role authenticated;
select throws_ok($$select remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'product',pg_temp.cid('supply'))$$,'42501',null,'cashier cannot remove catalog records');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.cid('owner'),'role','authenticated')::text,true);
select throws_ok($$select remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'product',pg_temp.cid('item-other'))$$,'42501',null,'foreign tenant denied');
select throws_ok($$select remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'product',pg_temp.cid('second-item'))$$,'42501',null,'foreign branch denied');
select throws_ok($$select remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'invoices',pg_temp.cid('supply'))$$,'42501',null,'arbitrary table names denied');
select is(remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'product',pg_temp.cid('supply')),'deleted','unused product deleted');
select is(remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'product',pg_temp.cid('item-salon')),'archived','stock history retained');
select is((select is_active from inventory_items where id=pg_temp.cid('item-salon')),false,'archived product unavailable');
select is(inventory_item_balance(pg_temp.cid('item-salon')),10::numeric,'removal does not change stock ledger');
select is(remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'service',pg_temp.cid('service-salon')),'archived','JSON promo references protect services');
select is(remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'promo',pg_temp.cid('unused-promo')),'deleted','unused promo deleted');
select is(remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'staff',pg_temp.cid('unused-staff')),'deleted','unused staff deleted');
select is(remove_business_record(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'resource',pg_temp.cid('unused-resource')),'deleted','unused resource deleted');
select is(remove_business_record(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),'room',pg_temp.cid('unused-room')),'deleted','unused room deleted');
select throws_ok($$select remove_business_record(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),'room',pg_temp.cid('occupied-room'))$$,'22023',null,'occupied room protected');
reset role;
select ok(exists(select 1 from audit_events where entity_id=pg_temp.cid('supply') and event_type='product.deleted'),'removal audited');
set constraints all immediate;
select * from finish();
rollback;
