begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
create function pg_temp.cid(text) returns uuid language sql immutable as $$select md5('checkout-test-'||$1)::uuid$$;
insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.cid(u),'00000000-0000-0000-0000-000000000000','authenticated','authenticated',u||'@checkout.example.test','',now(),'{}','{}',now(),now() from unnest(array['owner','outsider','cashier','technician'])u;
insert into organizations(id,name,slug,industry) select pg_temp.cid(v),v,'checkout-test-'||replace(v,'_','-'),v from unnest(array['salon','pet_care','automotive','hospitality'])v;
insert into organizations(id,name,slug,industry) values(pg_temp.cid('other'),'Other','checkout-test-other','salon');
insert into organization_memberships(id,organization_id,user_id,role) select pg_temp.cid('member-'||v),pg_temp.cid(v),pg_temp.cid('owner'),'owner' from unnest(array['salon','pet_care','automotive','hospitality'])v;
insert into organization_memberships(id,organization_id,user_id,role) values(pg_temp.cid('cashier-member'),pg_temp.cid('salon'),pg_temp.cid('cashier'),'cashier'),(pg_temp.cid('tech-member'),pg_temp.cid('salon'),pg_temp.cid('technician'),'technician'),(pg_temp.cid('other-member'),pg_temp.cid('other'),pg_temp.cid('outsider'),'owner');
insert into branches(id,organization_id,name,is_primary) select pg_temp.cid('branch-'||v),pg_temp.cid(v),'Main',true from unnest(array['salon','pet_care','automotive','hospitality','other'])v;
insert into branches(id,organization_id,name,is_primary) values(pg_temp.cid('second-branch'),pg_temp.cid('salon'),'Other',false);
insert into membership_branch_assignments(organization_id,membership_id,branch_id) values(pg_temp.cid('salon'),pg_temp.cid('cashier-member'),pg_temp.cid('branch-salon'));
insert into customers(id,organization_id,full_name) select pg_temp.cid('customer-'||v),pg_temp.cid(v),'Checkout Client' from unnest(array['salon','pet_care','automotive','hospitality','other'])v;
insert into services(id,organization_id,name,duration_minutes,base_price_centavos) select pg_temp.cid('service-'||v),pg_temp.cid(v),'Existing service',30,10000 from unnest(array['salon','pet_care'])v;
insert into inventory_items(id,organization_id,branch_id,name,sku,category,unit,sell_price_centavos,product_purpose) select pg_temp.cid('item-'||v),pg_temp.cid(v),pg_temp.cid('branch-'||v),'Retail bottle','BOTTLE','Care','bottle',2500,'retail' from unnest(array['salon','pet_care','automotive','hospitality','other'])v;
insert into inventory_items(id,organization_id,branch_id,name,unit,sell_price_centavos,product_purpose) values(pg_temp.cid('second-item'),pg_temp.cid('salon'),pg_temp.cid('second-branch'),'Other branch','piece',1000,'retail'),(pg_temp.cid('supply'),pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'Internal supply','ml',500,'internal');
insert into inventory_movements(organization_id,branch_id,inventory_item_id,movement_type,quantity_delta,note) select organization_id,branch_id,id,'opening',10,'Test opening stock' from inventory_items where sku='BOTTLE';
-- Canonical appointment snapshots; no product quantities are inferred from past visits.
insert into appointments(id,organization_id,branch_id,customer_id,starts_at,expected_duration_minutes,status) select pg_temp.cid('appointment-'||v),pg_temp.cid(v),pg_temp.cid('branch-'||v),pg_temp.cid('customer-'||v),now()-interval '1 hour',30,'completed' from unnest(array['salon','pet_care'])v;
insert into appointment_services(appointment_id,service_id) select pg_temp.cid('appointment-'||v),pg_temp.cid('service-'||v) from unnest(array['salon','pet_care'])v;
insert into pet_profiles(id,organization_id,customer_id,name,species) values(pg_temp.cid('pet'),pg_temp.cid('pet_care'),pg_temp.cid('customer-pet_care'),'Test pet','dog');
insert into pet_appointment_details(appointment_id,organization_id,pet_id,customer_id_snapshot,pet_name_snapshot) values(pg_temp.cid('appointment-pet_care'),pg_temp.cid('pet_care'),pg_temp.cid('pet'),pg_temp.cid('customer-pet_care'),'Test pet');
insert into vehicles(id,organization_id,customer_id,make,model,plate_number) values(pg_temp.cid('vehicle'),pg_temp.cid('automotive'),pg_temp.cid('customer-automotive'),'Toyota','Test','CHECKOUT-01');
insert into services(id,organization_id,name,duration_minutes,base_price_centavos) values(pg_temp.cid('service-automotive'),pg_temp.cid('automotive'),'Approved labor',30,10000);
insert into job_orders(id,organization_id,branch_id,customer_id,vehicle_id,job_number,status) values(pg_temp.cid('job'),pg_temp.cid('automotive'),pg_temp.cid('branch-automotive'),pg_temp.cid('customer-automotive'),pg_temp.cid('vehicle'),1,'ready_for_release');
insert into job_order_items(organization_id,job_order_id,service_id,service_name_snapshot,quantity,unit_price_centavos,line_total_centavos,duration_minutes) values(pg_temp.cid('automotive'),pg_temp.cid('job'),pg_temp.cid('service-automotive'),'Approved labor',1,10000,10000,30);
create temporary table ctx(name text primary key,id uuid,line uuid,bill uuid);
grant all on ctx to authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.cid('owner'),'role','authenticated')::text,true);
-- Neutral invoice adapter fixtures for automotive and hospitality; existing charges are not recreated by checkout.
insert into ctx(name,bill) select v,create_manual_invoice(pg_temp.cid(v),pg_temp.cid('branch-'||v),'Checkout Client') from unnest(array['hospitality'])v;
select add_manual_invoice_charge(bill,'Existing agreed charge',1,10000,pg_temp.cid('charge-'||name)) from ctx;
select create_estimate(pg_temp.cid('job'),0,0,null);
select record_estimate_authorization((select id from estimates where job_order_id=pg_temp.cid('job')),'approve','in_person','Agreed service');
insert into ctx(name,bill) values('automotive',issue_invoice(pg_temp.cid('job'),(select id from estimates where job_order_id=pg_temp.cid('job')),null));
set local role authenticated;
insert into ctx(name,id) select v,open_checkout(pg_temp.cid('branch-'||v),pg_temp.cid('appointment-'||v),null,null,pg_temp.cid('open-'||v)) from unnest(array['salon','pet_care'])v;
update ctx set id=open_checkout(pg_temp.cid('branch-'||name),null,bill,null,pg_temp.cid('open-'||name)) where bill is not null;
select is((get_checkout(id)->>'total')::bigint,10000::bigint,name||': existing charge appears') from ctx;
select ok(get_checkout(id) ?& array['timezone','baseLines','promos','products','invoices','payments'],name||': checkout reader returns the complete page contract') from ctx;
select is(jsonb_typeof(get_checkout(id)->'products'),'array',name||': empty product list remains renderable') from ctx;
select is(open_checkout(pg_temp.cid('branch-salon'),pg_temp.cid('appointment-salon'),null,null,pg_temp.cid('open-salon')),(select id from ctx where name='salon'),'open retry returns same checkout');
select is(jsonb_array_length(search_checkout_products((select id from ctx where name='salon'),'BOTTLE','Care',1)),1,'bounded search finds product by SKU and category');
select is((select count(*) from checkout_lines),0::bigint,'viewing product creates no commercial or stock record');
select throws_ok($$select save_checkout_product((select id from ctx where name='salon'),null,null,pg_temp.cid('item-other'),1,pg_temp.cid('foreign-product'))$$,'42501',null,'foreign tenant product denied');
select throws_ok($$select save_checkout_product((select id from ctx where name='salon'),null,null,pg_temp.cid('second-item'),1,pg_temp.cid('branch-product'))$$,'42501',null,'foreign branch product denied');
select throws_ok($$select save_checkout_product((select id from ctx where name='salon'),null,null,pg_temp.cid('supply'),1,pg_temp.cid('supply-product'))$$,'42501',null,'internal supplies not sold as retail');
update ctx set line=save_checkout_product(id,null,null,pg_temp.cid('item-'||name),2,pg_temp.cid('add-'||name));
select is((get_checkout(id)->>'total')::bigint,15000::bigint,name||': product increases total') from ctx;
select is(inventory_item_balance(pg_temp.cid('item-salon')),10::numeric,'acceptance does not deduct physical stock');
select is(inventory_available_balance(pg_temp.cid('item-salon')),8::numeric,'acceptance reserves stock');
select is(save_checkout_product((select id from ctx where name='salon'),null,null,pg_temp.cid('item-salon'),2,pg_temp.cid('add-salon')),(select line from ctx where name='salon'),'add retry does not duplicate line');
select throws_ok($$select save_checkout_product((select id from ctx where name='salon'),null,null,pg_temp.cid('item-salon'),99,pg_temp.cid('too-many'))$$,'P0001',null,'insufficient stock rejected');
select lives_ok($$select save_checkout_product(id,line,2,pg_temp.cid('item-salon'),1.5,pg_temp.cid('edit')) from ctx where name='salon'$$,'fractional native quantity can be changed');
select is((get_checkout((select id from ctx where name='salon'))->>'total')::bigint,13750::bigint,'fractional quantity uses exact stored price');
select throws_ok($$select save_checkout_product(id,line,2,pg_temp.cid('item-salon'),1,pg_temp.cid('stale')) from ctx where name='salon'$$,'40001',null,'stale edit rejected');
select lives_ok($$select save_checkout_product(id,line,3,pg_temp.cid('item-salon'),0,pg_temp.cid('remove')) from ctx where name='salon'$$,'unfulfilled draft line can be removed');
select is(inventory_available_balance(pg_temp.cid('item-salon')),10::numeric,'removal releases reservation');
update ctx set line=save_checkout_product(id,null,null,pg_temp.cid('item-salon'),2,pg_temp.cid('readd')) where name='salon';
select lives_ok($$select fulfill_checkout_product(id,line,1,'handover',pg_temp.cid('handover-'||name)) from ctx$$,'explicit handover works for every adapter');
select lives_ok($$select fulfill_checkout_product(id,line,1,'handover',pg_temp.cid('handover-'||name)) from ctx$$,'handover retry is safe');
select is(inventory_item_balance(pg_temp.cid('item-salon')),9::numeric,'handover deducted exactly once');
select throws_ok($$select consume_inventory_reservation((select reservation_id from checkout_lines where id=(select line from ctx where name='salon')),1,'raw-bypass')$$,'42501',null,'raw reservation RPC cannot bypass checkout');
select throws_ok($$select reserve_inventory_ledger(null,'checkout_line',null,1,'bypass')$$,'42501',null,'private ledger cannot be called directly');
select lives_ok($$select finalize_checkout(id,pg_temp.cid('finalize-'||name)) from ctx$$,'each adapter posts additional invoice');
select lives_ok($$select finalize_checkout(id,pg_temp.cid('finalize-'||name)) from ctx$$,'finalize retry does not duplicate invoice');
select is((select count(*) from checkout_invoices),4::bigint,'one additional invoice per checkout');
select throws_ok($$select save_checkout_product(id,line,(select version from checkout_lines where id=ctx.line),pg_temp.cid('item-salon'),3,pg_temp.cid('posted-edit')) from ctx where name='salon'$$,'22023',null,'posted financial line cannot be rewritten');
select lives_ok($$select record_checkout_payment(id,12000,'cash',null,current_date,pg_temp.cid('pay-'||name)) from ctx$$,'partial payment allocates existing and additional bills');
select lives_ok($$select record_checkout_payment(id,12000,'cash',null,current_date,pg_temp.cid('pay-'||name)) from ctx$$,'payment exact retry safe');
select is((get_checkout(id)->>'balance')::bigint,3000::bigint,name||': shared remaining balance correct') from ctx;
select is((select count(*) from payments where status='paid'),8::bigint,'one allocation per document, no duplicate payments');
select throws_ok($$select record_checkout_payment(id,4000,'cash',null,current_date,pg_temp.cid('overpay')) from ctx where name='salon'$$,'22023',null,'overpayment rejected server-side');
select lives_ok($$select fulfill_checkout_product(id,line,1,'return',pg_temp.cid('return')) from ctx where name='salon'$$,'physical return supported');
select lives_ok($$select fulfill_checkout_product(id,line,1,'return',pg_temp.cid('return')) from ctx where name='salon'$$,'return retry does not duplicate stock');
select is(inventory_item_balance(pg_temp.cid('item-salon')),10::numeric,'return restores stock');
select is((get_checkout((select id from ctx where name='salon'))->>'paid')::bigint,12000::bigint,'physical return never refunds payment');
select lives_ok($$select save_checkout_product(id,null,null,pg_temp.cid('item-salon'),1,pg_temp.cid('later-sale')) from ctx where name='salon'$$,'additional products allowed before later payment');
select throws_ok($$select record_checkout_payment(id,100,'cash',null,current_date,pg_temp.cid('draft-pay')) from ctx where name='salon'$$,'22023',null,'payment cannot skip draft review');
select lives_ok($$select finalize_checkout(id,pg_temp.cid('later-finalize')) from ctx where name='salon'$$,'later products create separate additional invoice');
select is((get_checkout((select id from ctx where name='salon'))->>'balance')::bigint,5500::bigint,'later purchase increases balance without rewriting paid invoice');
insert into ctx(name,id) values('retail',open_checkout(pg_temp.cid('branch-salon'),null,null,pg_temp.cid('customer-salon'),pg_temp.cid('retail-open')));
update ctx set line=save_checkout_product(id,null,null,pg_temp.cid('item-salon'),1,pg_temp.cid('retail-add')) where name='retail';
select lives_ok($$select finalize_checkout(id,pg_temp.cid('retail-finalize')) from ctx where name='retail'$$,'product-only sale posts without fake operation');
select is((get_checkout((select id from ctx where name='retail'))->>'total')::bigint,2500::bigint,'product-only bill total correct');
select ok(not(get_checkout((select id from ctx where name='retail'))::text like '%cost_price%'),'customer-safe summary has no cost data');
select lives_ok($$select get_checkout_product_report(pg_temp.cid('branch-salon'),1)$$,'product report reads stored snapshots');
select is((get_checkout_product_report(pg_temp.cid('branch-salon'),1)->>'sales')::bigint,10000::bigint,'product sales count additional invoices once');

-- Voids release only unfulfilled stock, preserving physical return history.
select lives_ok($$select void_invoice((select invoice_id from checkout_lines where id=(select line from ctx where name='retail')),'Customer cancelled before handover')$$,'void uncollected retail bill');
select is((select quantity_reserved-quantity_consumed-quantity_released from inventory_reservations where id=(select reservation_id from checkout_lines where id=(select line from ctx where name='retail'))),0::numeric,'void releases remaining reservation');
select throws_ok($$select fulfill_checkout_product(id,line,1,'handover',pg_temp.cid('void-handover')) from ctx where name='retail'$$,'22023',null,'voided product cannot be handed over');
-- New retail checkout for the cashier path below.
update ctx set id=open_checkout(pg_temp.cid('branch-salon'),null,null,pg_temp.cid('customer-salon'),pg_temp.cid('cashier-retail')) where name='retail';
update ctx set line=save_checkout_product(id,null,null,pg_temp.cid('item-salon'),1,pg_temp.cid('cashier-add')) where name='retail';
select throws_ok($$select transition_job(pg_temp.cid('job'),'complete')$$,'22023','Complete checkout payment before releasing the vehicle','retail balance blocks vehicle release even after base invoice paid');
select lives_ok($$select record_checkout_payment(id,3000,'cash',null,current_date,pg_temp.cid('auto-final-pay')) from ctx where name='automotive'$$,'automotive settles additional retail charges');
select is((select status::text from job_orders where id=pg_temp.cid('job')),'ready_for_release','payment does not release the vehicle automatically');
select lives_ok($$select transition_job(pg_temp.cid('job'),'complete')$$,'vehicle release remains explicit after all checkout bills are paid');
-- A real hospitality stay remains occupied after collecting money.
reset role;
insert into hospitality_rooms(id,organization_id,branch_id,name,capacity) values(pg_temp.cid('room'),pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),'101',2);
insert into hospitality_stays(id,organization_id,branch_id,room_id,guest_id,room_name_snapshot,guest_name_snapshot,occupants,request_key) values(pg_temp.cid('stay'),pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),pg_temp.cid('room'),pg_temp.cid('customer-hospitality'),'101','Checkout Client',1,pg_temp.cid('stay-key'));
insert into hospitality_stay_bills(organization_id,branch_id,stay_id,invoice_id) select pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),pg_temp.cid('stay'),bill from ctx where name='hospitality';
set local role authenticated;
select throws_ok($$select check_out_hospitality(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),pg_temp.cid('stay'),false)$$,'22023','Acknowledge the outstanding balance before checkout','product debt keeps room checkout acknowledgement authoritative');
select lives_ok($$select record_checkout_payment(id,3000,'cash',null,current_date,pg_temp.cid('hotel-final-pay')) from ctx where name='hospitality'$$,'guest settles base and product bill');
select is((select checked_out_at from hospitality_stays where id=pg_temp.cid('stay')),null::timestamptz,'payment does not clear occupancy');
select lives_ok($$select get_hospitality_workspace(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),current_date,current_date,'collections',1,'payments')$$,'hospitality collections include linked product payments');
select is((get_hospitality_workspace(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),current_date,current_date,'collections',1,'payments')->'finance'->>'collected')::bigint,15000::bigint,'hospitality collection report counts each allocation once');
select lives_ok($$select check_out_hospitality(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),pg_temp.cid('stay'),false)$$,'room checkout remains an explicit operation after settlement');
-- Promo inclusion price remains fixed and supplies stay out of retail checkout.
reset role;
insert into commerce_promos(id,organization_id,branch_id,name,price_centavos,currency,status,components) values(pg_temp.cid('promo'),pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'Included bottle bundle',11000,'PHP','active',jsonb_build_array(jsonb_build_object('kind','service','referenceId',pg_temp.cid('service-salon'),'quantity','1','unit','service'),jsonb_build_object('kind','product','referenceId',pg_temp.cid('item-salon'),'quantity','1','unit','bottle'),jsonb_build_object('kind','supply','referenceId',pg_temp.cid('supply'),'quantity','1','unit','ml')));
set local role authenticated;
insert into ctx(name,id) values('promo',book_appointment_with_promos(pg_temp.cid('promo-book'),pg_temp.cid('branch-salon'),pg_temp.cid('customer-salon'),null,null,null,array[pg_temp.cid('service-salon')],jsonb_build_array(jsonb_build_object('id',pg_temp.cid('promo'),'version',1)),now()+interval '2 days','{}','{}',null,null,false));
update ctx set id=open_checkout(pg_temp.cid('branch-salon'),id,null,null,pg_temp.cid('promo-open')) where name='promo';
select throws_ok($$select record_checkout_payment(id,11000,'cash',null,current_date,pg_temp.cid('skip-inclusions')) from ctx where name='promo'$$,'22023',null,'direct payment cannot skip included product review');
select lives_ok($$select accept_checkout_inclusions(id,pg_temp.cid('included')) from ctx where name='promo'$$,'included products reserved explicitly');
select lives_ok($$select accept_checkout_inclusions(id,pg_temp.cid('included-retry')) from ctx where name='promo'$$,'included product acceptance remains idempotent');
select is((select count(*) from checkout_lines where checkout_id=(select id from ctx where name='promo')),1::bigint,'internal supplies excluded and included retail is not duplicated');
select is((get_checkout((select id from ctx where name='promo'))->>'total')::bigint,11000::bigint,'included product never charged twice');
select lives_ok($$select finalize_checkout(id,pg_temp.cid('promo-finalize')) from ctx where name='promo'$$,'promo-only checkout finalizes without extra charge');
select is((select count(*) from checkout_invoices where checkout_id=(select id from ctx where name='promo')),0::bigint,'promo inclusion does not create product invoice revenue');
select lives_ok($$select get_appointment_report(pg_temp.cid('salon'),current_date-1,current_date,pg_temp.cid('branch-salon'))$$,'appointment reports read posted retail sales');
select is((get_appointment_report(pg_temp.cid('salon'),current_date-1,current_date,pg_temp.cid('branch-salon'))->'summary'->>'grossSalesCentavos')::bigint,17500::bigint,'service revenue and product revenue reconcile without promo double counting');
select is((get_appointment_report(pg_temp.cid('salon'),current_date-1,current_date,pg_temp.cid('branch-salon'))->'summary'->>'outstandingCentavos')::bigint,5500::bigint,'existing report includes product balances');
select ok(not exists(select 1 from checkout_invoices ci join invoices i on i.id=ci.invoice_id where i.total_centavos<>(select sum(recognized_revenue_centavos) from invoice_items where invoice_id=i.id)),'product revenue allocations reconcile to posted invoice totals');
insert into ctx(name,id) values('guest-retail',open_checkout(pg_temp.cid('branch-hospitality'),null,null,pg_temp.cid('customer-hospitality'),pg_temp.cid('guest-retail-open')));
update ctx set line=save_checkout_product(id,null,null,pg_temp.cid('item-hospitality'),1,pg_temp.cid('guest-retail-add')) where name='guest-retail';
select finalize_checkout(id,pg_temp.cid('guest-retail-finalize')) from ctx where name='guest-retail';
select is((get_hospitality_workspace(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),current_date,current_date,'outstanding',1,'payments')->>'rowCount')::bigint,1::bigint,'hospitality standalone product debt is visible');
select is(jsonb_array_length(get_hospitality_workspace(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),current_date,current_date,'outstanding',1,'payments')->'rows'),1,'hospitality retail balance has a navigable invoice row');
select record_checkout_payment(id,2500,'cash',null,current_date,pg_temp.cid('guest-retail-pay')) from ctx where name='guest-retail';
select ok(not exists(select 1 from jsonb_array_elements(get_hospitality_workspace(pg_temp.cid('hospitality'),pg_temp.cid('branch-hospitality'),current_date,current_date,'collections',1,'payments')->'rows') r where r->>'invoice_id' is null),'collection rows provide invoice links including standalone retail');
reset role;
set local "request.jwt.claims"='{"role":"anon"}';
select lives_ok($$update appointments set status='cancelled' where id=(select appointment_id from checkouts where id=(select id from ctx where name='promo'))$$,'authorized cancellation trigger releases inclusions without requiring a staff JWT');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.cid('owner'),'role','authenticated')::text,true);
set local role authenticated;
select throws_ok($$select release_inventory_reservation_ledger(null,1,'bypass',true)$$,'42501',null,'private cancellation release cannot be invoked by a client');
select is((select sum(quantity_reserved-quantity_consumed-quantity_released) from inventory_reservations where id in(select reservation_id from checkout_lines where checkout_id=(select id from ctx where name='promo'))),0::numeric,'cancelled promo releases uncollected included products');
reset role;
insert into inventory_items(id,organization_id,branch_id,name,unit,sell_price_centavos,product_purpose) values(pg_temp.cid('gift'),pg_temp.cid('salon'),pg_temp.cid('branch-salon'),'Complimentary bottle','bottle',0,'retail');
insert into inventory_movements(organization_id,branch_id,inventory_item_id,movement_type,quantity_delta) values(pg_temp.cid('salon'),pg_temp.cid('branch-salon'),pg_temp.cid('gift'),'opening',1);
set local role authenticated;
insert into ctx(name,id) values('gift',open_checkout(pg_temp.cid('branch-salon'),null,null,pg_temp.cid('customer-salon'),pg_temp.cid('gift-open')));
update ctx set line=save_checkout_product(id,null,null,pg_temp.cid('gift'),1,pg_temp.cid('gift-add')) where name='gift';
select finalize_checkout(id,pg_temp.cid('gift-finalize')) from ctx where name='gift';
select lives_ok($$select void_invoice((select invoice_id from checkout_lines where id=(select line from ctx where name='gift')),'Gift not collected')$$,'zero-priced posted products can still be voided before handover');
select is(inventory_available_balance(pg_temp.cid('gift')),1::numeric,'voiding complimentary product releases its reservation');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.cid('outsider'),'role','authenticated')::text,true);
select is((select count(*) from checkout_lines),0::bigint,'RLS hides other tenant checkout lines');
select throws_ok($$select fulfill_checkout_product(id,line,1,'handover',pg_temp.cid('foreign-handover')) from ctx where name='salon'$$,'42501',null,'other tenant cannot fulfill stock');
select throws_ok($$select search_checkout_products((select id from ctx where name='salon'))$$,'42501',null,'other tenant cannot search checkout catalog');

select throws_ok($$select get_checkout((select id from ctx where name='salon'))$$,'42501',null,'other tenant cannot read financial summary');
select throws_ok($$select record_checkout_payment((select id from ctx where name='salon'),100,'cash',null,current_date,pg_temp.cid('foreign-pay'))$$,'42501',null,'other tenant cannot pay');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.cid('technician'),'role','authenticated')::text,true);
select throws_ok($$select get_checkout((select id from ctx where name='salon'))$$,'42501',null,'service-only staff cannot read checkout finances');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.cid('cashier'),'role','authenticated')::text,true);
select lives_ok($$select fulfill_checkout_product(id,line,1,'handover',pg_temp.cid('cashier-handover')) from ctx where name='retail'$$,'cashier can hand over authorized checkout product');
select throws_ok($$select open_checkout(pg_temp.cid('second-branch'),null,null,pg_temp.cid('customer-salon'),pg_temp.cid('wrong-branch'))$$,'42501',null,'branch-restricted cashier cannot sell in another branch');
select throws_ok($$update checkout_lines set unit_price_centavos=1$$,'42501',null,'direct price writes denied');
reset role;
set local role anon;
select throws_ok($$select get_checkout(null)$$,'42501',null,'anonymous users cannot read checkout finances');
reset role;
set local role authenticated;
-- Walk-in purchases need no customer record or contact details.
insert into ctx(name,id) values('walk-in',open_checkout(pg_temp.cid('branch-salon'),null,null,null,pg_temp.cid('walk-in-open')));
select is(open_checkout(pg_temp.cid('branch-salon'),null,null,null,pg_temp.cid('walk-in-open')),(select id from ctx where name='walk-in'),'walk-in retry reuses checkout');
select is(get_checkout((select id from ctx where name='walk-in'))->>'customer','Walk-in customer','walk-in receipt label');
select is(get_checkout((select id from ctx where name='walk-in'))->>'customerId',null::text,'walk-in has no fake customer');
select throws_ok($$select open_checkout(pg_temp.cid('branch-salon'),null,null,pg_temp.cid('customer-other'),pg_temp.cid('walk-in-foreign'))$$,'42501',null,'optional customer must belong to tenant');
select throws_ok($$select open_checkout(pg_temp.cid('second-branch'),null,null,null,pg_temp.cid('walk-in-branch'))$$,'42501',null,'walk-in respects branch access');
update ctx set line=save_checkout_product(id,null,null,pg_temp.cid('item-salon'),1,pg_temp.cid('walk-in-add')) where name='walk-in';
select lives_ok($$select finalize_checkout(id,pg_temp.cid('walk-in-finalize')) from ctx where name='walk-in'$$,'walk-in posts without personal details');
select lives_ok($$select record_checkout_payment(id,2500,'cash',null,current_date,pg_temp.cid('walk-in-pay')) from ctx where name='walk-in'$$,'walk-in payment without mobile number');
select is((get_checkout((select id from ctx where name='walk-in'))->>'balance')::bigint,0::bigint,'walk-in balance settled');
reset role;
set constraints all immediate;
select * from finish();
rollback;
