import { notFound } from "next/navigation";
import { z } from "zod";
import { hospitalityContext } from "@/modules/hospitality/runtime";
import { canHospitality } from "@/modules/hospitality/contracts";
import { formatMoney } from "@/lib/operations";
import { PrintStatementButton } from "@/components/hospitality/print-button";
import { LoadError, dateLabel } from "@/components/hospitality/shared";
import { RecordTable } from "@/components/record-table";
export default async function Statement({ params }: { params: Promise<{ stayId: string }> }) {
  const [{ stayId }, { db, activeMembership: m }] = await Promise.all([params, hospitalityContext()]);
  if (!canHospitality(m.role, "financeRead") || !z.uuid().safeParse(stayId).success) notFound();
  const stay = await db.from("hospitality_stays").select("guest_name_snapshot,room_name_snapshot,checked_in_at,checked_out_at,branch_id,planned_checkout_at,stay_period_label").eq("organization_id", m.organizationId).eq("id", stayId).single();
  const link = await db.from("hospitality_stay_bills").select("invoice_id").eq("organization_id", m.organizationId).eq("stay_id", stayId).single();
  if (stay.error || link.error) notFound();
  const [bill, items, payments, branch] = await Promise.all([db.from("invoices").select("invoice_number,status,total_centavos,paid_centavos,balance_centavos").eq("id", link.data.invoice_id).single(), db.from("invoice_items").select("id,description_snapshot,quantity,unit_price_centavos,line_total_centavos").eq("invoice_id", link.data.invoice_id).order("id").limit(1001), db.from("payments").select("id,method,status,amount_centavos,reference,paid_at,cash_tendered_centavos,cash_change_centavos").eq("invoice_id", link.data.invoice_id).order("paid_at").limit(1001), db.from("branches").select("name,timezone").eq("id", stay.data.branch_id).single()]);
  if (bill.error || items.error || payments.error || items.data.length > 1000 || payments.data.length > 1000) return <LoadError>Statement is unavailable. Review the paginated stay ledger.</LoadError>;
  return <main id="hospitality-stay-statement" className="mx-auto max-w-4xl space-y-5 rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl">{m.organizationName}</h1><p className="text-sm text-slate-500">Stay statement · {branch.data?.name}</p></div><PrintStatementButton/></div><p className="break-all text-xs text-slate-500">{bill.data.invoice_number}</p><p>{stay.data.guest_name_snapshot} · {stay.data.room_name_snapshot}</p><p className="text-sm">Check-in: {dateLabel(stay.data.checked_in_at, branch.data?.timezone ?? m.timezone)}</p>{stay.data.planned_checkout_at ? <p className="text-sm">{stay.data.stay_period_label} · Paid period ends {dateLabel(stay.data.planned_checkout_at, branch.data?.timezone ?? m.timezone)}</p> : null}<RecordTable id="hospitality-statement-charges" caption="Charges" columns={[{ key: "description", label: "Description" }, { key: "total", label: "Total", align: "right" }]} rows={items.data.map(i => ({ id: `statement-charge-${i.id}`, cells: { description: <>{i.description_snapshot}<small className="block">{i.quantity} × {formatMoney(i.unit_price_centavos)}</small></>, total: formatMoney(i.line_total_centavos) } }))}/><RecordTable id="hospitality-statement-payments" caption="Payments" columns={[{ key: "payment", label: "Payment" }, { key: "amount", label: "Amount", align: "right" }]} rows={payments.data.map(p => ({ id: `statement-payment-${p.id}`, cells: { payment: <>{p.method} · {p.status}<small className="block">{dateLabel(p.paid_at, branch.data?.timezone ?? m.timezone)} · {p.reference || "No reference"}</small>{p.cash_tendered_centavos !== null ? <small className="block">Cash received {formatMoney(p.cash_tendered_centavos)} · Change {formatMoney(p.cash_change_centavos ?? 0)}</small> : null}</>, amount: formatMoney(p.amount_centavos) } }))}/><dl className="ml-auto grid max-w-sm grid-cols-2 gap-2 text-sm"><dt>Total charges</dt><dd className="text-right">{formatMoney(bill.data.total_centavos)}</dd><dt>Paid (net of reversals)</dt><dd className="text-right">{formatMoney(bill.data.paid_centavos)}</dd><dt>Balance</dt><dd className="text-right">{formatMoney(bill.data.balance_centavos)}</dd></dl><p className="text-xs text-slate-500">Record of room charges and payments received by the business. Cash change is excluded from the amount collected. This is not a NegOSu subscription receipt or proof of gateway processing.</p></main>;
}
