import { formatMoney } from "@/lib/operations";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Pencil, Users } from "lucide-react";
import { z } from "zod";
import { petContext } from "@/modules/pet-care/runtime";
import { groomingStatus } from "@/modules/pet-care/pets";
import { PageHeader } from "@/components/page-patterns";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
export default async function Page({ params, searchParams }: { params: Promise<{ petId: string }>; searchParams: Promise<{ tab?: string }> }) {
 const [{ petId }, query, { db, activeMembership, enabled }] = await Promise.all([params,searchParams,petContext()]);
 if (!z.uuid().safeParse(petId).success) notFound();
 const { data: pet } = await db.from("pet_profiles").select("*").eq("id",petId).eq("organization_id",activeMembership.organizationId).single();
 if (!pet) notFound();
 const [{ data: owner }, visits, notes] = await Promise.all([db.from("customers").select("full_name").eq("id",pet.customer_id).eq("organization_id",activeMembership.organizationId).single(),db.from("pet_appointment_details").select("appointment_id,pickup_status,appointments!inner(starts_at,status,appointment_services(service_name_snapshot,unit_price_centavos))").eq("pet_id",pet.id).eq("organization_id",activeMembership.organizationId),db.from("pet_grooming_notes").select("id,note,next_visit_on,created_at,pet_appointment_details!inner(pet_id)").eq("pet_appointment_details.pet_id",pet.id).eq("organization_id",activeMembership.organizationId).order("created_at",{ascending:false})]);
 const tab = ["appointments","history"].includes(query.tab ?? "") ? query.tab : "overview";
 return <main id="pet-detail-page" className="mx-auto min-w-0 max-w-5xl"><Button asChild variant="ghost"><Link href="/dashboard/pet-care/pets"><ArrowLeft size={16} aria-hidden="true"/>Pets</Link></Button><PageHeader id="pet-detail-header" title={pet.name} description={`${pet.species} · ${pet.breed || "Breed not recorded"} · Owner: ${owner?.full_name ?? "Pet owner"}`} action={enabled && ["owner","manager","advisor"].includes(activeMembership.role) ? <Button asChild variant="secondary"><Link id="pet-detail-edit-button" href={`/dashboard/pet-care/pets?dialog=edit&petId=${pet.id}`}><Pencil size={16} aria-hidden="true"/>Edit</Link></Button> : undefined}/><Link id="pet-owner-profile-link" href={`/dashboard/customers/${pet.customer_id}`} className="mt-3 inline-flex min-h-11 items-center gap-2 text-sm underline"><Users size={16} aria-hidden="true"/>Owner profile</Link><nav id="pet-detail-tabs" className="mt-4 flex gap-3 overflow-x-auto border-b text-sm">{[["overview","Overview"],["appointments","Appointments"],["history","Grooming History"]].map(([key,label]) => <Link id={`pet-tab-${key}`} key={key} href={`?tab=${key}`} aria-current={tab===key?"page":undefined} className={`min-h-11 whitespace-nowrap px-2 py-3 ${tab===key?"border-b-2 border-brand-primary text-brand-primary":"text-admin-text-secondary"}`}>{label}</Link>)}</nav>
 {tab==="overview" ? <Card className="mt-4 p-4"><dl className="grid gap-4 text-sm sm:grid-cols-2">{[["Status",pet.is_active?"Active":"Inactive"],["Date of birth",pet.date_of_birth],["Size",pet.size_category],["Coat",pet.coat],["Grooming preferences",pet.grooming_preferences],["Owner-reported handling cautions (internal)",pet.handling_cautions]].map(([label,value])=><div key={label}><dt className="text-admin-text-secondary">{label}</dt><dd className="mt-1 [overflow-wrap:anywhere]">{value||"Not recorded"}</dd></div>)}</dl><p className="mt-4 text-xs text-admin-text-secondary">Owner-reported information is not professionally verified. Handling cautions are excluded from customer links.</p></Card> : <div className="mt-4 grid gap-3">{visits.error ? <p role="alert">Unable to load grooming visits.</p> : visits.data?.filter(v=>{const a=Array.isArray(v.appointments)?v.appointments[0]:v.appointments;return tab!=="history"||a?.status==="completed";}).map(v=>{const a=Array.isArray(v.appointments)?v.appointments[0]:v.appointments;return <Card key={v.appointment_id} className="p-4"><Link id={`pet-history-${v.appointment_id}`} className="text-sm underline" href={`/dashboard/pet-care/appointments/${v.appointment_id}`}>{a?.starts_at ? new Intl.DateTimeFormat("en-PH",{timeZone:activeMembership.timezone,dateStyle:"medium"}).format(new Date(a.starts_at)) : "Appointment"} · {groomingStatus(a?.status??"",v.pickup_status)}</Link><p className="mt-1 text-sm">{a?.appointment_services.map(s=>`${s.service_name_snapshot} · ${formatMoney(s.unit_price_centavos, activeMembership.currency)}`).join(", ")}</p></Card>;})}{!visits.error&&!visits.data?.some(v=>{const a=Array.isArray(v.appointments)?v.appointments[0]:v.appointments;return tab!=="history"||a?.status==="completed";})?<p className="text-sm">No grooming visits yet.</p>:null}</div>}{tab==="history"?<Card id="pet-history-notes" className="mt-4 p-4"><h2 className="text-base font-medium">Grooming observations</h2>{notes.error?<p role="alert">Unable to load visit notes.</p>:notes.data?.length?notes.data.map(n=><article key={n.id} className="mt-3 border-t pt-3 text-sm"><p className="whitespace-pre-wrap [overflow-wrap:anywhere]">{n.note}</p>{n.next_visit_on?<p className="mt-1 text-admin-text-secondary">Recommended return: {n.next_visit_on}</p>:null}</article>):<p className="mt-3 text-sm">No grooming notes yet.</p>}</Card>:null}</main>;
}
