import {CheckoutPrintButton} from "@/components/checkout-print-button";
import Link from "next/link";
import {loadCheckout} from "@/modules/core/checkout/runtime";
import {CheckoutOrder,CheckoutSummary} from "@/components/checkout-summary";
import {FormMessage} from "@/components/form-message";
import {formatMoney} from "@/lib/operations";
export default async function Page({params,searchParams}:{params:Promise<{checkoutId:string}>;searchParams:Promise<{message?:string}>}){
 const [{checkoutId},q]=await Promise.all([params,searchParams]);const {checkout:c,m}=await loadCheckout(checkoutId);
 return <main id="checkout-receipt" className="mx-auto min-w-0 max-w-3xl"><div className="print:hidden"><Link id="receipt-back-checkout" className="inline-flex min-h-11 items-center underline" href={`/dashboard/checkout/${c.id}`}>Back to checkout</Link><Link id="receipt-back-transaction" className="ml-4 inline-flex min-h-11 items-center underline" href={c.appointmentId?`/dashboard/${m.industry==="pet_care"?"pet-care/":""}appointments/${c.appointmentId}`:c.sourceInvoiceId?`/dashboard/invoices/${c.sourceInvoiceId}`:"/dashboard/checkout/new"}>Back to transaction</Link><CheckoutPrintButton/><FormMessage message={q.message}/></div><header className="my-5"><h1 className="text-2xl">{m.organizationName}</h1><p>{m.branchName}</p><h2 className="mt-4 text-xl">{c.hasDraft||c.balance>0?"Order statement":"Payment receipt"}</h2><p>{c.customer}</p><p className="text-sm">{new Intl.DateTimeFormat("en-PH",{timeZone:m.timezone,dateStyle:"medium",timeStyle:"short"}).format(new Date(c.createdAt))}</p><p className="text-sm">{c.invoices.map(i=>i.number).join(" · ")}</p></header><div className="space-y-4"><CheckoutOrder checkout={c}/><CheckoutSummary checkout={c}/><section className="rounded-xl border border-admin-border bg-white p-4"><h2>Payments</h2>{c.payments.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 border-b py-3 text-sm"><span>{new Intl.DateTimeFormat("en-PH",{timeZone:m.timezone,dateStyle:"medium"}).format(new Date(p.date))} · {p.method.replaceAll("_"," ")} · {p.status}{p.reference?` · ${p.reference}`:""}</span><span>{formatMoney(p.amount,p.currency)}</span></div>)}{!c.payments.length?<p className="mt-3 text-sm">No payments recorded.</p>:null}</section></div><p className="mt-4 text-sm">Payment does not confirm product handover or complete a visit, vehicle release, pet collection or room checkout.</p></main>;
}
