import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { z } from "zod";
import { Save, X, Calendar, Check, CreditCard, Link as LinkIcon, Plus } from "lucide-react";
import { petContext } from "@/modules/pet-care/runtime";
import { groomingActions, groomingActionLabels, groomingStatus } from "@/modules/pet-care/pets";
import { calculateAppointmentPaymentSummary, paymentMethods } from "@/modules/core/payments/payment.service";
import { createPetLink, payPetAppointment, transitionPet, reschedulePetAppointment, addGroomingNote } from "@/app/dashboard/pet-care/actions";
import { FormDialog } from "@/components/management-ui";
import { PageHeader, SectionHeader } from "@/components/page-patterns";
import { FormMessage } from "@/components/form-message";
import { FormActions } from "@/components/form-actions";
import { SubmitButton } from "@/components/submit-button";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { formatMoney, formatDuration } from "@/lib/operations";
export default async function Page({ params, searchParams }: { params: Promise<{ appointmentId: string }>; searchParams: Promise<{ error?: string; link?: string; dialog?: string }> }) {
 const [{ appointmentId }, query, { db, activeMembership, enabled, branchTimezone }] = await Promise.all([params,searchParams,petContext()]);
 if (!z.uuid().safeParse(appointmentId).success) notFound();
 const { data: a } = await db.from("appointments").select("id,customer_id,branch_id,branches(name,timezone),status,source,starts_at,expected_duration_minutes,customer_note,internal_note,expected_total_centavos,appointment_services(service_name_snapshot,unit_price_centavos,duration_minutes)").eq("id",appointmentId).eq("organization_id",activeMembership.organizationId).single();
 if (!a || !activeMembership.branches.some(branch => branch.id === a.branch_id)) notFound();
 const [{ data: d }, { data: customer }, payments, staff, resources, notes] = await Promise.all([
  db.from("pet_appointment_details").select("pet_id,pet_name_snapshot,pickup_status,collected_at").eq("appointment_id",a.id).single(),
  db.from("customers").select("full_name").eq("id",a.customer_id).eq("organization_id",activeMembership.organizationId).single(),
  db.from("payments").select("id,currency,amount_centavos,status,method,reference,paid_at").eq("appointment_id",a.id).eq("organization_id",activeMembership.organizationId).order("paid_at",{ascending:false}),
  db.from("appointment_staff_assignments").select("organization_staff_profiles(full_name)").eq("appointment_id",a.id),
  db.from("appointment_resource_assignments").select("scheduling_resources(name)").eq("appointment_id",a.id),
  db.from("pet_grooming_notes").select("id,note,next_visit_on,created_at").eq("appointment_id",a.id).order("created_at",{ascending:false}),
 ]);
 if (!d) notFound();
 const appointmentBranch = Array.isArray(a.branches) ? a.branches[0] : a.branches;
 const timezone = appointmentBranch?.timezone ?? branchTimezone;
 const canManage = enabled && ["owner","manager","advisor"].includes(activeMembership.role), canPay = enabled && ["owner","manager","cashier"].includes(activeMembership.role);
 const summary = calculateAppointmentPaymentSummary(a.expected_total_centavos,(payments.data ?? []).map(p => ({ amountCentavos: p.amount_centavos, status: p.status })));
 const valueName = (v: unknown, key: string) => { const o = Array.isArray(v) ? v[0] : v; return (o as Record<string,string> | null)?.[key] ?? ""; };
 const href = `/dashboard/pet-care/appointments/${a.id}`;
 const editable = ["requested","confirmed"].includes(a.status);
 const actions = groomingActions(a.status,d.pickup_status);
 const schedule = new Intl.DateTimeFormat("en-PH", {timeZone:timezone,dateStyle:"medium",timeStyle:"short"});
 return <main id="pet-appointment-detail" className="mx-auto min-w-0 max-w-5xl [overflow-wrap:anywhere]">
 <PageHeader id="pet-appointment-header" eyebrow={`${a.source.replaceAll("_"," ")} · ${groomingStatus(a.status,d.pickup_status)}`} title={d.pet_name_snapshot} description={`${customer?.full_name ?? "Pet owner"} · ${appointmentBranch?.name ?? activeMembership.branchName}`} action={<>
 {canManage && editable?<Button asChild variant="secondary"><Link id="pet-appointment-reschedule-button" href={`${href}?dialog=reschedule`}><Calendar size={16} aria-hidden="true"/>Reschedule</Link></Button>:null}
 <Button asChild variant="ghost"><Link id="pet-appointment-close-button" href="/dashboard/pet-care/appointments"><X size={16} aria-hidden="true"/>Close</Link></Button></>}/><FormMessage error={query.error}/>
 <Card id="pet-appointment-scheduling-assignments" className="mt-6 p-5"><h2 className="font-medium">Scheduling assignments</h2>{staff.error||resources.error?<p role="alert" className="mt-3 text-sm">Scheduling assignments could not be loaded.</p>:<dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-admin-text-secondary">Scheduled groomer</dt><dd className="font-medium">{staff.data?.map(row=>valueName(row.organization_staff_profiles,"full_name")).filter(Boolean).join(", ")||"Unassigned"}</dd></div><div><dt className="text-admin-text-secondary">Grooming resource</dt><dd className="font-medium">{resources.data?.map(row=>valueName(row.scheduling_resources,"name")).filter(Boolean).join(", ")||"Unassigned"}</dd></div></dl>}</Card>
 <div className="mt-6 grid min-w-0 items-start gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
 <div className="grid min-w-0 gap-5">
 <Card id="pet-appointment-visit-details" className="p-5"><h2 className="font-medium">Visit details</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">
 <div><dt className="text-admin-text-secondary">Schedule</dt><dd className="font-medium">{schedule.format(new Date(a.starts_at))}</dd></div><div><dt className="text-admin-text-secondary">Estimated duration</dt><dd className="font-medium">{a.expected_duration_minutes?formatDuration(a.expected_duration_minutes):"—"}</dd></div>
 <div><dt className="text-admin-text-secondary">Owner notes</dt><dd className="whitespace-pre-wrap">{a.customer_note||"None"}</dd></div><div><dt className="text-admin-text-secondary">Internal notes</dt><dd className="whitespace-pre-wrap">{a.internal_note||"None"}</dd></div></dl>
 <h3 className="mt-6 font-medium">Services</h3><div className="mt-2 divide-y divide-admin-border">{a.appointment_services.map((s,i)=><div key={i} className="flex justify-between gap-3 py-3 text-sm"><span className="min-w-0">{s.service_name_snapshot}<span className="mt-1 block text-xs text-admin-text-secondary">{formatDuration(s.duration_minutes)}</span></span><span className="shrink-0">{formatMoney(s.unit_price_centavos, activeMembership.currency)}</span></div>)}</div><div className="mt-3 flex flex-wrap justify-between gap-2 font-medium"><span>Estimated total</span><span>{formatMoney(a.expected_total_centavos, activeMembership.currency)}</span></div>
 <Button asChild variant="ghost" className="mt-4 max-w-full"><Link id="pet-appointment-profile-link" href={`/dashboard/pet-care/pets/${d.pet_id}`}><LinkIcon size={16} aria-hidden="true"/>Pet profile</Link></Button></Card>
 </div><div className="grid min-w-0 gap-5">
 <Card id="pet-appointment-actions-card" className="p-5"><h2 className="font-medium">Actions</h2>{canManage&&actions.length?<div id="pet-visit-actions" className="mt-4 grid gap-3">{actions.map(action=><form key={action} action={transitionPet}><input type="hidden" name="appointmentId" value={a.id}/><input type="hidden" name="action" value={action}/><SubmitButton id={`pet-${action === "ready" ? "ready-for-pickup" : action === "collect" ? "collected" : action}-button`} className="w-full" variant={["cancel","no_show"].includes(action)?"destructive":"secondary"} pendingText="Updating…">{["cancel","no_show"].includes(action)?<X size={16} aria-hidden="true"/>:<Check size={16} aria-hidden="true"/>}{groomingActionLabels[action]}</SubmitButton></form>)}</div>:<p className="mt-3 text-sm text-admin-text-secondary">{canManage?"No further visit actions are available.":"You have read-only access to this visit."}</p>}</Card>
 {canManage && editable?<Card id="pet-appointment-customer-self-service" className="p-5"><SectionHeader id="pet-customer-self-service-header" title="Customer self-service" description="Private confirmation and reschedule link." action={<form action={createPetLink}><input type="hidden" name="appointmentId" value={a.id}/><SubmitButton id="pet-create-link-button" pendingText="Creating…" variant="secondary" size="sm"><LinkIcon size={16} aria-hidden="true"/>Create link</SubmitButton></form>}/>{query.link?.match(/^\/appointment\/[A-Za-z0-9_-]{43}$/)?<Link id="pet-customer-link" className="mt-3 block break-all text-sm underline" href={query.link}>{query.link}</Link>:<p className="mt-3 text-sm text-admin-text-secondary">Create a private link to share with the owner.</p>}</Card>:null}
 <Card id="pet-payment-summary" className="p-5"><div id="pet-payment-header" className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-medium">Payment</h2>{canPay&&!payments.error&&summary.balanceCentavos>0?<Button asChild size="sm"><Link id="pet-record-payment-toggle" href={`${href}?dialog=payment`}><CreditCard size={16} aria-hidden="true"/>Record payment</Link></Button>:null}</div>{payments.error?<p role="alert" className="mt-3 text-sm">Payments could not be loaded.</p>:<><dl className="mt-3 grid gap-3 rounded-xl bg-admin-surface-muted p-3 text-sm sm:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3">{[["Total",summary.totalCentavos],["Paid",summary.paidCentavos],["Balance",summary.balanceCentavos]].map(([label,amount])=><div key={label}><dt className="text-admin-text-secondary">{label}</dt><dd className="font-medium">{formatMoney(Number(amount), activeMembership.currency)}</dd></div>)}</dl><p className="mt-2 text-xs font-medium text-admin-text-secondary">{summary.status}</p><div className="mt-3 divide-y divide-admin-border">{payments.data?.map(p=><div id={`pet-payment-${p.id}`} key={p.id} className="flex justify-between gap-3 py-2 text-sm"><span className="min-w-0 capitalize">{p.method.replaceAll("_"," ")}<small className="block text-admin-text-secondary">{p.reference||p.status}</small></span><span className="shrink-0">{formatMoney(p.amount_centavos, p.currency)}</span></div>)}</div><p className="mt-3 text-xs text-admin-text-secondary">Payment and collection are separate actions.</p></>}</Card>
 </div></div>
 <Card id="pet-grooming-notes" className="mt-5 p-5"><SectionHeader id="pet-grooming-notes-header" title="Grooming visit notes" action={canManage&&["checked_in","in_service","completed"].includes(a.status)?<Button asChild size="sm" variant="secondary"><Link id="pet-grooming-note-add-button" href={`${href}?dialog=note`}><Plus size={16} aria-hidden="true"/>Add note</Link></Button>:null}/><p className="mt-1 text-xs text-admin-text-secondary">Internal grooming observations and return recommendations. Notes are retained in visit history and excluded from public links.</p>{notes.error?<p role="alert" className="mt-3 text-sm">Visit notes could not be loaded.</p>:<div className="mt-3 grid gap-3">{notes.data?.map(n=><article id={`pet-note-${n.id}`} key={n.id} className="rounded-xl border border-admin-border p-3 text-sm"><p className="whitespace-pre-wrap [overflow-wrap:anywhere]">{n.note}</p><p className="mt-2 text-xs text-admin-text-secondary">{new Intl.DateTimeFormat("en-PH",{timeZone:timezone,dateStyle:"medium",timeStyle:"short"}).format(new Date(n.created_at))}{n.next_visit_on?` · Recommended return: ${n.next_visit_on}`:""}</p></article>)}{!notes.data?.length?<p className="text-sm text-admin-text-secondary">No grooming notes yet.</p>:null}</div>}</Card>
 {canPay&&!payments.error&&summary.balanceCentavos>0&&query.dialog==="payment"?<FormDialog id="pet-payment-dialog" title="Record payment" closeHref={href} size="md"><form id="pet-payment-form" action={payPetAppointment} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="appointmentId" value={a.id}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label className="text-sm">Amount ({activeMembership.currency})<Input id="pet-payment-amount" name="amount" inputMode="decimal" defaultValue={(summary.balanceCentavos/100).toFixed(2)} required/></label><label className="text-sm">Method<select id="pet-payment-method" name="method" className="min-h-11 w-full rounded-xl border border-admin-border px-3">{paymentMethods.map(method=><option key={method} value={method}>{method.replaceAll("_"," ")}</option>)}</select></label><label className="col-span-full text-sm">Reference (optional)<Input id="pet-payment-reference" name="reference" maxLength={100}/></label><FormActions id="pet-payment-actions" cancelHref={href}><SubmitButton id="pet-payment-save" pendingText="Recording…"><CreditCard size={16} aria-hidden="true"/>Record payment</SubmitButton></FormActions></form></FormDialog>:null}
 {canManage&&["checked_in","in_service","completed"].includes(a.status)&&query.dialog==="note"?<FormDialog id="pet-grooming-note-dialog" title="Add grooming visit note" closeHref={href}><form id="pet-grooming-note-form" action={addGroomingNote} className="mt-4 grid gap-3"><input type="hidden" name="appointmentId" value={a.id}/><input type="hidden" name="id" value={randomUUID()}/><label className="text-sm">Grooming result and observations<textarea id="pet-grooming-note-input" name="note" required maxLength={3000} className="mt-2 min-h-24 w-full rounded-xl border border-admin-border p-3"/></label><label className="text-sm">Recommended return date (optional)<Input id="pet-grooming-next-visit" name="nextVisitOn" type="date" className="mt-2"/></label><FormActions id="pet-grooming-note-actions" cancelHref={`/dashboard/pet-care/appointments/${a.id}`}><SubmitButton id="pet-grooming-note-save" pendingText="Saving…"><Save size={16} aria-hidden="true"/>Save visit note</SubmitButton></FormActions></form></FormDialog>:null}
 {canManage && query.dialog === "reschedule" && ["requested","confirmed"].includes(a.status) ? <FormDialog id="pet-reschedule-dialog" title="Reschedule grooming" closeHref={`/dashboard/pet-care/appointments/${a.id}`}><form id="pet-reschedule-form" action={reschedulePetAppointment} className="grid gap-4"><input type="hidden" name="appointmentId" value={a.id}/><p className="text-sm">Pet, services, prices, groomer, and resources stay with this appointment.</p><label className="text-sm">New appointment time ({timezone})<Input id="pet-reschedule-time" name="startsAt" type="datetime-local" required className="mt-2"/></label><FormActions id="pet-reschedule-actions" cancelHref={`/dashboard/pet-care/appointments/${a.id}`}><SubmitButton id="pet-reschedule-save" pendingText="Rescheduling…"><Calendar size={16} aria-hidden="true"/>Save time</SubmitButton></FormActions></form></FormDialog> : null}</main>;
}
