"use client";
import { CatalogItemThumbnail } from "@/components/catalog-item-thumbnail";
import { promoServiceIds } from "@/modules/core/commerce/appointment-promos";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {ServiceThumbnail} from "@/components/service-thumbnail";
import {formatMoney} from "@/lib/operations";
import type {PublicShop} from "@/lib/public-booking";
import {publicBookingSelection,type PublicPromo} from "@/lib/public-promos";

export function BookingSelection({shop,promos,branchId,serviceIds,promoIds}:{shop:PublicShop;promos:PublicPromo[];branchId:string;serviceIds:string[];promoIds:string[]}){
 const [branch,setBranch]=useState(branchId),[services,setServices]=useState(serviceIds),[selectedPromos,setSelectedPromos]=useState(promoIds);
 const selected=publicBookingSelection(shop.services,promos,branch,services,selectedPromos);
 function selectPromo(p:PublicPromo,checked:boolean){setServices(current=>current.filter(id=>!promoServiceIds(p).includes(id)));setSelectedPromos(current=>[...current.filter(id=>!promos.some(row=>row.id===id && promoServiceIds(row).some(sid=>promoServiceIds(p).includes(sid)))),...(checked?[p.id]:[])]);}
 return <form id="public-booking-availability-form" className="mt-4 space-y-5"><input type="hidden" name="step" value="2"/><input type="hidden" name="selection" value="1"/>
 <label className="block text-sm font-medium">Location<select id="public-booking-branch-select" name="branch" value={branch} onChange={e=>{setBranch(e.target.value);setSelectedPromos([]);}} className="mt-2 min-h-11 w-full rounded-ui-md border border-admin-border bg-white px-3">{shop.branches.filter(b=>b.acceptsBookings).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
 <fieldset id="public-booking-service-options"><legend className="font-medium">Services</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{shop.services.map(s=><label key={s.id} className="flex min-w-0 cursor-pointer gap-3 rounded-ui-md border border-admin-border p-3 has-[:checked]:border-brand-primary has-[:checked]:bg-brand-tint"><input id={`public-booking-service-${s.id}`} type="checkbox" className="mt-1 size-4 shrink-0" checked={services.includes(s.id)&&!selected.promos.some(p=>promoServiceIds(p).includes(s.id))} onChange={e=>{setSelectedPromos(current=>current.filter(id=>!promos.some(p=>p.id===id && promoServiceIds(p).includes(s.id))));setServices(current=>e.target.checked?[...current.filter(id=>id!==s.id),s.id]:current.filter(id=>id!==s.id));}}/><CatalogItemThumbnail id={`booking-service-image-${s.id}`} url={s.thumbnailUrl} name={s.name}/><span className="min-w-0"><strong className="block text-sm">{s.name}</strong><span className="mt-1 block text-sm text-admin-text-secondary">{s.durationMinutes} min · From {formatMoney(s.priceCentavos,s.currency??shop.currency)}</span></span></label>)}</div></fieldset>
 {promos.some(p=>p.branchId===branch)?<fieldset id="public-booking-promo-options"><legend className="font-medium">Or choose a promo</legend><p className="mt-1 text-sm text-admin-text-secondary">A promo includes all its services for one fixed price. Selecting it replaces overlapping services or promos.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{promos.filter(p=>p.branchId===branch).map(p=><label key={p.id} className="min-w-0 cursor-pointer rounded-ui-md border border-admin-border p-3 has-[:checked]:border-brand-primary has-[:checked]:bg-brand-tint"><ServiceThumbnail id={`booking-promo-image-${p.id}`} url={p.imageUrl} name={p.name} subject="promo"/><span className="mt-2 flex items-start gap-3"><input id={`public-booking-promo-${p.id}`} type="checkbox" className="mt-1 size-4 shrink-0" checked={selectedPromos.includes(p.id)} onChange={e=>selectPromo(p,e.target.checked)}/><span><strong className="block">{p.name}</strong><span className="mt-1 block text-sm">{formatMoney(p.priceCentavos,p.currency)} · {p.durationMinutes} min</span><span className="mt-1 block text-sm text-admin-text-secondary">{[...promoServiceIds(p).map(id=>shop.services.find(s=>s.id===id)?.name),...p.inclusions.map(i=>`${i.name} (${i.quantity} ${i.unit})`)].filter(Boolean).join(", ")}</span>{p.validFrom||p.validThrough?<span className="mt-1 block text-sm text-admin-text-secondary">{p.validFrom?`From ${p.validFrom}`:"Available now"}{p.validThrough?` · Through ${p.validThrough}`:""}</span>:null}</span></span></label>)}</div></fieldset>:null}
 {selected.services.map(s=><input key={s.id} type="hidden" name="services" value={s.id}/>)}{selected.promos.map(p=><input key={p.id} type="hidden" name="promos" value={p.id}/>)}
 <p id="public-booking-service-selection-summary" className="text-sm font-medium">{selected.services.length?`${selected.services.length} selected · ${selected.durationMinutes} min · ${selected.services.every(s=>selected.promos.some(p=>promoServiceIds(p).includes(s.id)))?"":"From "}${formatMoney(selected.priceCentavos,shop.currency)}`:"Choose a service or promo to continue."}</p>
 {selected.services.length>10?<p role="alert" className="text-sm text-status-danger">Select no more than 10 services in total, including services inside promos.</p>:null}
 <Button id="public-booking-show-availability-button" type="submit" disabled={!selected.services.length||selected.services.length>10} className="w-full sm:w-auto">Continue to date</Button></form>;
}
