import Link from "next/link";
import {CheckoutOrder,CheckoutSummary} from "@/components/checkout-summary";
import {FormMessage} from "@/components/form-message";
import {Input} from "@/components/ui/input";
import {SubmitButton} from "@/components/submit-button";
import {paymentMethods} from "@/modules/core/payments/payment.service";
import {payCheckout} from "@/app/dashboard/checkout/actions";
import type {Checkout} from "@/modules/core/checkout/contracts";
export function CheckoutPayment({checkout:c,timezone,error}:{checkout:Checkout;timezone:string;error?:string}){
 const href=`/dashboard/checkout/${c.id}`;
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:timezone}).format(new Date());
 return <main id="payment-page" className="mx-auto min-w-0 max-w-6xl"><Link id="payment-back-checkout" className="inline-flex min-h-11 items-center underline" href={href}>Back to checkout</Link><h1 className="text-2xl">Payment</h1><p>{c.customer}</p><FormMessage error={error}/><div id="payment-order-summary" className="mt-5 grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]"><CheckoutOrder checkout={c}/><CheckoutSummary checkout={c}/></div>{c.hasDraft?<p role="alert" className="mt-4">Return to checkout and finalize the additional products before payment.</p>:c.balance>0?<form id="checkout-payment-form" action={payCheckout} className="mt-4 grid gap-4 rounded-xl border border-admin-border bg-white p-4 shadow-sm sm:grid-cols-2"><input type="hidden" name="checkoutId" value={c.id}/><input type="hidden" name="request" value={crypto.randomUUID()}/><label className="text-sm">Amount ({c.currency})<Input id="payment-amount-input" name="amount" inputMode="decimal" defaultValue={(c.balance/100).toFixed(2)} required/></label><label className="text-sm">Payment method<select id="payment-method-select" name="method" className="min-h-11 w-full rounded-xl border border-admin-border bg-white px-3">{paymentMethods.map(method=><option key={method} value={method}>{method.replaceAll("_"," ")}</option>)}</select></label><label className="text-sm">Reference (optional)<Input id="payment-reference-input" name="reference" maxLength={100}/></label><label className="text-sm">Payment date<Input id="payment-date-input" type="date" name="date" defaultValue={today} max={today} required/></label><p className="text-sm sm:col-span-2">Partial payments are allowed. Record money already received; this does not charge a card or complete the business operation.</p><SubmitButton id="payment-submit-button" pendingText="Recording…">Record payment</SubmitButton></form>:<div className="mt-4 rounded-xl border p-4"><p>No remaining balance.</p><Link id="payment-view-receipt" className="inline-flex min-h-11 items-center underline" href={`${href}/receipt`}>View receipt</Link></div>}</main>;
}
