import type {ReactNode} from "react";
import {formatMoney} from "@/lib/operations";
import type {Checkout} from "@/modules/core/checkout/contracts";
export function CheckoutSummary({checkout:c,children}:{checkout:Checkout;children?:ReactNode}){
 const money=(n:number)=>formatMoney(n,c.currency);
 return <aside id="checkout-summary" className="min-w-0 rounded-xl border border-admin-border bg-white p-4 shadow-sm"><h2 className="text-lg">Order summary</h2><dl className="mt-4 space-y-3 text-sm">{[["Subtotal",c.total+c.discount-c.tax],["Discount",c.discount],["Tax",c.tax],["Total",c.total],["Paid",c.paid],["Balance",c.balance]].map(([label,value])=><div key={label} className="flex justify-between gap-4"><dt>{label}</dt><dd id={`checkout-${String(label).toLowerCase()}`} className={label==="Balance"||label==="Total"?"text-lg font-medium":""}>{money(Number(value))}</dd></div>)}</dl>{children?<div className="mt-5 space-y-3 print:hidden">{children}</div>:null}</aside>;
}
export function CheckoutOrder({checkout:c}:{checkout:Checkout}){
 return <section id="checkout-order-lines" className="min-w-0 rounded-xl border border-admin-border bg-white p-4 shadow-sm"><h2 className="text-lg">Order</h2><div id="checkout-services-section" className="divide-y divide-admin-border">{c.baseLines.map((line,index)=><div key={index} className="flex justify-between gap-3 py-3 text-sm"><div className="min-w-0 break-words">{line.name}<p className="text-admin-text-secondary">{line.quantity} × {formatMoney(line.unitPrice,c.currency)}</p></div><span className="shrink-0">{formatMoney(line.amount,c.currency)}</span></div>)}</div>{c.promos.map(p=><p key={p.id} className="mb-3 text-sm text-admin-text-secondary">{p.name} includes: {p.services.join(", ")}</p>)}{c.products.map(line=><div key={line.id} className="flex justify-between gap-3 border-t border-admin-border py-3 text-sm"><div className="min-w-0 break-words">{line.name}<p className="text-admin-text-secondary">{line.quantity} {line.unit} × {formatMoney(line.unit_price_centavos,c.currency)}</p>{line.included_key?<p>Included in {line.promo_name}</p>:null}{line.invoiceStatus==="void"?<p>Voided</p>:null}</div><span className="shrink-0">{line.invoiceStatus==="void"?"Voided":line.included_key?"Included":formatMoney(line.line_total_centavos,c.currency)}</span></div>)}{!c.baseLines.length&&!c.products.length?<p className="py-4 text-sm">No products added yet.</p>:null}</section>;
}
