import { expect, test } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { createHash, randomUUID } from "node:crypto";
import { authenticatedSmokeEnabled, loginAsOwner, qaPersonaCredentials } from "./helpers/auth";

const local = (url?: string) => !!url && ["localhost", "127.0.0.1"].includes(new URL(url).hostname);
test.skip(!authenticatedSmokeEnabled() || !local(process.env.E2E_BASE_URL) || !local(process.env.NEXT_PUBLIC_SUPABASE_URL), "Requires isolated local fixtures.");
test.use({ trace: "off" });
for (const industry of ["automotive", "salon", "pet_care"] as const) {
  test(`${industry} guided chat, staff reply, message limits and booking handoff`, async ({ page, browser }) => {
    test.setTimeout(100_000);
    const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
    const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false } });
    const credentials = industry === "pet_care" ? { email: process.env.QA_PET_OWNER_EMAIL!, password: process.env.QA_OWNER_PASSWORD! } : qaPersonaCredentials(industry);
    const auth = await db.auth.signInWithPassword(credentials); expect(auth.error).toBeNull();
    const member = await db.from("organization_memberships").select("organization_id").eq("user_id", auth.data.user!.id).single(); expect(member.error).toBeNull();
    const org = await admin.from("organizations").select("id,slug,public_page_enabled").eq("id", member.data!.organization_id).single(); expect(org.error).toBeNull();
    const branch = await admin.from("branches").select("id,accepts_public_bookings,opening_hours").eq("organization_id", org.data!.id).eq("is_primary", true).single(); expect(branch.error).toBeNull();
    const service = await admin.from("services").select("id,is_public").eq("organization_id", org.data!.id).eq("is_active", true).limit(1).single(); expect(service.error).toBeNull();
    const staffContext = await browser.newContext({ baseURL: process.env.E2E_BASE_URL });
    const staff = await staffContext.newPage();
    let token = "";
    try {
      expect((await admin.from("organizations").update({ public_page_enabled: true }).eq("id", org.data!.id)).error).toBeNull();
      expect((await admin.from("branches").update({ accepts_public_bookings: true }).eq("id", branch.data!.id)).error).toBeNull();
      expect((await admin.from("services").update({ is_public: true }).eq("id", service.data!.id)).error).toBeNull();
      await page.setViewportSize({ width: 320, height: 800 });
      await page.goto(`/shop/${org.data!.slug}`);
      expect((await page.request.get("/api/dashboard/notifications")).status()).toBe(401);
      await page.evaluate(() => window.scrollTo({ top: 300, behavior: "instant" }));
      const backgroundScroll = await page.evaluate(() => scrollY);
      expect(backgroundScroll).toBeGreaterThan(0);
      await page.locator("#public-chat-open").click();
      await expect(page.locator("#public-chat-dialog")).toBeVisible();
      expect(await page.locator("html").evaluate(element => getComputedStyle(element).overflowY)).toBe("hidden");
      await page.mouse.move(2, 300); await page.mouse.wheel(0, 500);
      expect(await page.evaluate(() => scrollY)).toBe(backgroundScroll);
      await page.locator("#public-chat-close").click();
      expect(await page.evaluate(() => scrollY)).toBe(backgroundScroll);
      expect(await page.locator("html").evaluate(element => getComputedStyle(element).overflowY)).not.toBe("hidden");
      await page.locator("#public-chat-open").click();
      await page.locator("#public-chat-branch").selectOption(branch.data!.id);
      await page.locator("#public-chat-service").selectOption(service.data!.id);
      await expect(page.locator("#public-chat-answer")).toContainText("minutes");
      await page.locator("#public-chat-topic-hours").click();
      await page.locator("#public-chat-topic-location").click();
      await page.locator("#public-chat-topic-message").click();
      await page.locator("#public-chat-name").fill("Chat Browser Customer");
      await page.locator("#public-chat-suggestion-booking").click();
      await expect(page.locator("#public-chat-message")).toHaveValue(/I.d like to book/);
      await page.locator("#public-chat-message").fill("Can I book this service?");
      await page.locator("#public-chat-send").click();
      await expect(page.locator("#public-chat-messages")).toContainText("Can I book this service?");
      await expect(page.locator("#public-chat-message-limit")).toContainText("2 messages left");
      token = await page.evaluate(slug => sessionStorage.getItem(`negosu-chat:${slug}`)!, org.data!.slug);
      const conversation = await admin.from("customer_conversations").select("id,branch_id").eq("token_hash", createHash("sha256").update(token).digest("hex")).single(); expect(conversation.error).toBeNull(); expect(conversation.data!.branch_id).toBe(branch.data!.id);
      if (industry === "pet_care") { await staff.goto("/login?industry=pet_care"); await staff.locator("#negosu-login-email-input").fill(credentials.email); await staff.locator("#negosu-login-password-input").fill(credentials.password); await staff.locator("#negosu-login-submit-button").click(); await expect(staff.locator("#pet-care-dashboard")).toBeVisible(); }
      else await loginAsOwner(staff, industry);
      await staff.goto("/dashboard/inbox");
      const initialAlerts = await staff.request.get("/api/dashboard/notifications?organizationId=foreign&branchId=foreign");
      expect(initialAlerts.status()).toBe(200);
      expect(initialAlerts.headers()["cache-control"]).toContain("no-store");
      const initialAttention = await initialAlerts.json();
      expect(initialAttention.organizationId).toBe(org.data!.id);
      expect(initialAttention.branchId).toBe(branch.data!.id);
      const initialMessages = initialAttention.items.find((item: { id: string }) => item.id === "messages").count;
      await staff.locator("#dashboard-notification-bell").click();
      await expect(staff.locator("#dashboard-notification-messages")).toBeVisible();
      await staff.locator("#dashboard-notification-messages").click();
      await expect(staff).toHaveURL(/inbox\?tab=needs_reply/);
      await expect(staff.locator("#dashboard-notification-dialog")).not.toBeVisible();
      await staff.locator(`#inbox-conversation-${conversation.data!.id}`).click();
      await expect(staff.locator("#inbox-messages")).toContainText("Can I book this service?");
      await staff.locator("#inbox-reply").fill("Yes, choose your preferred time using Book an appointment.");
      await staff.locator("#inbox-send-reply").click();
      await expect(staff.locator("#inbox-messages")).toContainText("Yes, choose your preferred time");
      const afterReply = await (await staff.request.get("/api/dashboard/notifications")).json();
      expect(afterReply.items.find((item: { id: string }) => item.id === "messages")?.count ?? 0).toBe(initialMessages - 1);
      await expect(page.locator("#public-chat-messages")).toContainText("Yes, choose your preferred time", { timeout: 20_000 });
      // Concurrent requests cannot bypass the remaining-message limit.
      const responses = await Promise.all(Array.from({ length: 5 }, (_, index) => admin.rpc("send_customer_chat", { p_slug: org.data!.slug, p_token: token, p_request_id: randomUUID(), p_body: `Follow up ${index + 1}` })));
      expect(responses.filter(result => !result.error)).toHaveLength(2);
      expect(responses.filter(result => result.error?.code === "P0003")).toHaveLength(3);
      await expect(page.locator("#public-chat-limit-reached")).toContainText("three messages", { timeout: 20_000 });
      await expect(page.locator("#public-chat-message-form")).toHaveCount(0);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      const bookBounds = await page.locator("#public-chat-book").boundingBox();
      expect(bookBounds!.y + bookBounds!.height).toBeLessThanOrEqual(800);
      await page.screenshot({ path: `/private/tmp/negosu-chat-${industry}-mobile.png` });
      await staff.setViewportSize({ width: 320, height: 800 });
      expect(await staff.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await staff.screenshot({ path: `/private/tmp/negosu-chat-inbox-${industry}-mobile.png` });
      await page.locator("#public-chat-book").click();
      await expect(page).toHaveURL(new RegExp(`branch=${branch.data!.id}.*service=${service.data!.id}`));
      await expect(page.locator("#public-booking-request-form")).toBeVisible();
      await expect(page.locator('input[name="customerName"]')).toHaveValue("Chat Browser Customer");
      await expect(page.locator("#public-booking-notes-input")).toContainText("Can I book this service?");
      await staff.locator("#inbox-close-conversation").click();
      await expect(staff.locator("#inbox-reopen-conversation")).toBeVisible();
      await page.setViewportSize({ width: 1440, height: 900 });
      await page.goto(`/shop/${org.data!.slug}`); await page.locator("#public-chat-open").click(); await page.locator("#public-chat-topic-message").click();
      await expect(page.locator("#public-chat-limit-reached")).toContainText("closed");
      await page.screenshot({ path: `/private/tmp/negosu-chat-${industry}-desktop.png` });
      await page.locator("#public-chat-close").click();
      await expect(page.locator("#public-chat-dialog")).not.toBeVisible();
      await expect(page.locator("#public-chat-open")).toBeFocused();
    } finally {
      if (token) await admin.from("customer_conversations").delete().eq("token_hash", createHash("sha256").update(token).digest("hex"));
      await admin.from("organizations").update({ public_page_enabled: org.data!.public_page_enabled }).eq("id", org.data!.id);
      await admin.from("branches").update({ accepts_public_bookings: branch.data!.accepts_public_bookings }).eq("id", branch.data!.id);
      await admin.from("services").update({ is_public: service.data!.is_public }).eq("id", service.data!.id);
      await staffContext.close(); await db.auth.signOut({scope:"local"});
    }
  });
}
