import { test, expect } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { authenticatedSmokeEnabled } from "./helpers/auth";
import { selectRecord } from "./helpers/searchable-select";
const local = (url?: string) => !!url && ["127.0.0.1", "localhost"].includes(new URL(url).hostname);
test.skip(!authenticatedSmokeEnabled() || !local(process.env.E2E_BASE_URL) || !local(process.env.NEXT_PUBLIC_SUPABASE_URL), "Requires local Pet Care fixtures.");
test.use({ trace: "off" });
test("Pet Care explains closed hours, retains its draft, and books with groomer and resource", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 });
  await page.goto("/login?industry=pet_care");
  await page.locator("#negosu-login-email-input").fill(process.env.QA_PET_OWNER_EMAIL!);
  await page.locator("#negosu-login-password-input").fill(process.env.QA_OWNER_PASSWORD!);
  await page.locator("#negosu-login-submit-button").click();
  await expect(page.locator("#pet-care-dashboard")).toBeVisible();
  await page.goto("/dashboard/pet-care/appointments?dialog=create");
  await selectRecord(page, "pet-appointment-pet-select", { name: "Milo" });
  await selectRecord(page, "pet-appointment-service-select", { name: "Nail trim" });
  await page.locator("#pet-appointment-staff-select").click();
  await page.locator("#pet-appointment-staff-select-options").getByRole("option").first().click();
  await page.locator("#pet-appointment-resource-select").click();
  await page.locator("#pet-appointment-resource-select-options").getByRole("option").first().click();
  const day = new Date(); day.setUTCDate(day.getUTCDate() + 40); if (day.getUTCDay() === 0) day.setUTCDate(day.getUTCDate() + 1);
  const date = day.toISOString().slice(0,10);
  await page.locator("#pet-appointment-time-input").fill(`${date}T03:00`);
  await page.locator("#pet-appointment-save-button").click();
  await expect(page.locator("#pet-appointment-error")).toContainText(/hours|closed/i);
  await expect(page.locator("#pet-appointment-pet-select")).toHaveValue(/Milo/);
  await expect(page.locator("#pet-appointment-selected-services")).toContainText("Nail trim");
  await page.locator("#pet-appointment-time-input").fill(`${date}T10:00`);
  await page.locator("#pet-appointment-save-button").click();
  await expect(page).toHaveURL(/\/dashboard\/pet-care\/appointments\/[a-f0-9-]+$/);
  const id = new URL(page.url()).pathname.split("/").at(-1)!;
  const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
  const result = await db.from("appointments").select("id,appointment_staff_assignments(staff_profile_id),appointment_resource_assignments(resource_id)").eq("id", id).single();
  expect(result.error).toBeNull();
  expect(result.data?.appointment_staff_assignments).toHaveLength(1);
  expect(result.data?.appointment_resource_assignments).toHaveLength(1);
  await page.locator("#pet-cancel-button").click();
  await expect(page.locator("#pet-cancel-button")).toHaveCount(0);
});
