import Link from "next/link";
import {notFound} from "next/navigation";
import {getDashboardContext} from "@/lib/auth/context";
import {createClient} from "@/lib/supabase/server";
import {formatMoney} from "@/lib/operations";
import {checkoutRoles} from "@/modules/core/checkout/contracts";
import {RecordTable} from "@/components/record-table";
type ProductReport={sales:number;paid:number;balance:number;rows:Array<{inventory_item_id:string;name:string;unit:string;sold:number;sales:number;included:number;handed_over:number;returned:number}>};
export default async function Page({searchParams}:{searchParams:Promise<{page?:string}>}){
 const [{activeMembership:m},q,db]=await Promise.all([getDashboardContext(),searchParams,createClient()]);if(!checkoutRoles.includes(m.role))notFound();
 const page=Math.max(1,Math.min(10000,Number(q.page)||1));const {data,error}=await db.rpc("get_checkout_product_report",{p_branch:m.branchId,p_page:page});const report=data as ProductReport|null;
 return <main id="product-sales-report" className="mx-auto min-w-0 max-w-6xl"><Link className="inline-flex min-h-11 items-center underline" href="/dashboard/reports">Back to reports</Link><h1 className="text-2xl">Product sales & handover</h1><p className="mt-2 text-sm">{m.branchName} · All time. Posted product bills only; voided bills are excluded from sales. Promo inclusions have no additional revenue. Physical returns and refunds remain separate.</p>{error||!report?<p role="alert" className="mt-4">Unable to load product sales. Apply checkout setup and try again.</p>:<><dl className="my-4 grid gap-3 sm:grid-cols-3">{[["Product sales",report.sales],["Collected on product bills",report.paid],["Product bill balance",report.balance]].map(([label,value])=><div key={label} className="rounded-xl border border-admin-border bg-white p-4"><dt className="text-sm">{label}</dt><dd className="mt-2 text-xl">{formatMoney(Number(value),m.currency)}</dd></div>)}</dl><RecordTable id="product-sales-table" caption="Products sold and fulfilled" columns={[{key:"name",label:"Product"},{key:"sold",label:"Sold",secondary:true},{key:"included",label:"Included",secondary:true},{key:"handed",label:"Handed over",secondary:true},{key:"returned",label:"Returned",secondary:true},{key:"amount",label:"Sales",align:"right"}]} rows={report.rows.map((r,index)=>({id:`product-sales-${r.inventory_item_id}-${index}`,cells:{name:<>{r.name}<small className="block">{r.unit}</small></>,sold:r.sold,included:r.included,handed:r.handed_over,returned:r.returned,amount:formatMoney(r.sales,m.currency)},mobile:<p>Sold {r.sold} · Included {r.included} · Handed over {r.handed_over} · Returned {r.returned}</p>}))} empty="No product sales yet."/><nav className="mt-4 flex justify-between" aria-label="Product sales pages">{page>1?<Link className="p-3 underline" href={`?page=${page-1}`}>Previous</Link>:<span/>}{report.rows.length===50?<Link className="p-3 underline" href={`?page=${page+1}`}>Next</Link>:null}</nav></>}</main>;
}
