/** Guarded local integration: discounts, extensions, deposits, receipts and races. */
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
if (process.env.NODE_ENV === "production" || !["localhost", "127.0.0.1", "::1"].includes(new URL(url).hostname)) throw new Error("Local database required");
const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
async function main() {
 const f = JSON.parse(await readFile("/private/tmp/negosu-hospitality-fixture.json", "utf8"));
 let passed = 0;
 const ok = (message: string) => console.log(`ok ${++passed} - ${message}`);
 async function actor(role: string) { const db = createClient(url, key, { auth: { persistSession: false } }); assert.equal((await db.auth.signInWithPassword({ email: `qa.hospitality.${role}@negosu.local.test`, password: "NegOSu-Local-QA-2026!" })).error, null); return db; }
 async function call(db: SupabaseClient, name: string, args: Record<string, unknown>) { const r = await db.rpc(name, args); assert.equal(r.error, null, r.error?.message); return r.data; }
 const owner = await actor("owner"), cashier = await actor("cashier"), other = await actor("other"), front = await actor("frontdesk"), viewer = await actor("viewer"), housekeeper = await actor("housekeeper");
 const rates = [180,360,720,1440,10080,43200].map((durationMinutes, i) => ({ id: crypto.randomUUID(), label: ["3 hours","6 hours","12 hours","1 day","Weekly","Monthly"][i], durationMinutes, priceCentavos: 100000, extensionHourlyCentavos: 15000 }));
 const roomArgs = { p_org: f.org, p_branch: f.branch, p_room: null, p_name: `Pricing ${crypto.randomUUID().slice(0, 8)}`, p_type: "Test", p_description: "Local pricing test", p_capacity: 2, p_active: true, p_rates: rates, p_expected_version: 0 };
 const room = await call(owner, "save_hospitality_room_with_rates", roomArgs); ok("six periods and per-package extension prices saved");
 for (const bad of [-1, 0.5, 10000000001, null]) assert.ok((await owner.rpc("save_hospitality_room_with_rates", { ...roomArgs, p_name: crypto.randomUUID(), p_rates: [{ ...rates[0], extensionHourlyCentavos: bad }] })).error); ok("invalid hourly prices rejected");
 const arrival = { p_org: f.org, p_branch: f.branch, p_room: room, p_rate: rates[5].id, p_rates_version: 1, p_tendered: 150000, p_method: "cash", p_reference: "", p_occupants: 1, p_guest_name: "", p_guest: null, p_notes: "", p_request: crypto.randomUUID(), p_final: 80000, p_discount_type: "pwd", p_discount_card: "TEST-1234", p_deposit: 30000, p_receipt: "PAPER-001" };
 for (const change of [{ p_final: -1 }, { p_final: 100001 }, { p_discount_type: "none" }, { p_discount_card: "" }, { p_discount_type: "manual" }, { p_deposit: -1 }, { p_tendered: 109999 }, { p_method: "card" }, { p_receipt: "x".repeat(81) }]) assert.ok((await cashier.rpc("check_in_hospitality_cashier", { ...arrival, ...change })).error); ok("discount, card, deposit, receipt and sufficient tender validated in SQL");
 for (const db of [other, viewer, front, housekeeper]) assert.ok((await db.rpc("check_in_hospitality_cashier", arrival)).error); ok("arrival finance role and tenant boundaries enforced");
 assert.ok((await cashier.rpc("check_in_hospitality_cashier", { ...arrival, p_branch: f.annex })).error); ok("arrival branch restriction enforced");
 const race = await Promise.all([cashier.rpc("check_in_hospitality_cashier", arrival), owner.rpc("check_in_hospitality_cashier", arrival)]);
 assert.equal(race[0].error, null); assert.equal(race[1].error, null); assert.equal(race[0].data, race[1].data); const stayId = race[0].data; ok("duplicate concurrent discounted arrivals create one stay");
 const stay = (await owner.from("hospitality_stays").select("*").eq("id", stayId).single()).data!;
 assert.equal(Date.parse(stay.planned_checkout_at) - Date.parse(stay.checked_in_at), 30 * 86400000); ok("monthly duration is exactly thirty days");
 const link = (await owner.from("hospitality_stay_bills").select("*").eq("stay_id", stayId).single()).data!;
 const bill = (await owner.from("invoices").select("*").eq("id", link.invoice_id).single()).data!;
 const payment = (await owner.from("payments").select("*").eq("invoice_id", bill.id).single()).data!;
 assert.equal(bill.total_centavos, 80000); assert.equal(bill.paid_centavos, 80000); assert.equal(bill.balance_centavos, 0); assert.equal(bill.external_receipt_number, "PAPER-001");
 assert.equal(payment.cash_tendered_centavos, 150000); assert.equal(payment.cash_change_centavos, 40000); assert.equal(payment.cash_deposit_centavos, 30000); assert.equal(payment.receipt_number, "PAPER-001"); ok("net invoice revenue excludes deposit and cash change; receipt retained");
 assert.equal(link.rate_snapshot.discountCard, "TEST-1234"); assert.equal(link.rate_snapshot.finalCentavos, 80000); ok("original rate and discount metadata preserved in protected bill");
 for (const db of [other, viewer, housekeeper]) for (const table of ["hospitality_stay_bills", "invoice_deposits", "hospitality_stay_extensions"]) { const r = await db.from(table).select("*").eq("organization_id", f.org); assert.equal(r.error, null); assert.equal(r.data!.length, 0); } ok("operational and other-tenant roles cannot read finance metadata");
 assert.equal((await front.from("invoice_deposits").select("*").eq("invoice_id", bill.id)).data!.length, 1); ok("front desk can read deposit for checkout coordination");
 assert.ok((await cashier.from("invoice_deposits").update({ refunded_at: new Date().toISOString() }).eq("invoice_id", bill.id)).error); ok("direct deposit updates denied");
 assert.ok((await cashier.rpc("refund_invoice_deposit", { p_invoice: bill.id, p_method: "cash", p_reference: "" })).error); ok("internal refund primitive cannot bypass checkout workflow");
 await call(owner, "save_hospitality_room_with_rates", { ...roomArgs, p_room: room, p_expected_version: 1, p_rates: rates.map(r => ({ ...r, extensionHourlyCentavos: 90000 })) });
 const extension = { p_org: f.org, p_branch: f.branch, p_stay: stayId, p_expected_end: stay.planned_checkout_at, p_hours: 2, p_rate: null, p_rates_version: 2, p_final: 25000, p_discount_type: "manual", p_discount_card: "", p_tendered: 30000, p_method: "cash", p_reference: "", p_receipt: "EXT-001", p_request: crypto.randomUUID() };
 for (const change of [{ p_hours: 0 }, { p_hours: 721 }, { p_final: 30001 }, { p_discount_type: "card" }, { p_tendered: 24999 }, { p_expected_end: null }]) assert.ok((await cashier.rpc("extend_hospitality_stay", { ...extension, ...change })).error); ok("extension validates duration, saved hourly price, discounts, tender and expected end");
 for (const db of [other, front, viewer, housekeeper]) assert.ok((await db.rpc("extend_hospitality_stay", extension)).error); ok("extension finance and tenant access enforced");
 assert.ok((await cashier.rpc("extend_hospitality_stay", { ...extension, p_branch: f.annex })).error); ok("extension branch restriction enforced");
 const extended = await Promise.all([cashier.rpc("extend_hospitality_stay", extension), owner.rpc("extend_hospitality_stay", { ...extension, p_request: crypto.randomUUID() })]);
 assert.equal(extended.filter(r => !r.error).length, 1); assert.equal(extended.find(r => r.error)!.error!.code, "40001");
 const record = (await owner.from("hospitality_stay_extensions").select("*").eq("stay_id", stayId).single()).data!;
 assert.equal(record.base_centavos, 30000); assert.equal(record.final_centavos, 25000); assert.equal(Date.parse(record.to_at)-Date.parse(record.from_at), 7200000); ok("concurrent extensions use agreed snapshot and extend once");
 const replay = { ...extension, p_request: record.request_key };
 assert.equal(await call(cashier, "extend_hospitality_stay", replay), record.id);
 assert.ok((await cashier.rpc("extend_hospitality_stay", { ...replay, p_receipt: "changed" })).error); ok("exact extension retry is safe and changed replay rejected");
 const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Manila" }).format(new Date());
 const reportArgs = { p_org: f.org, p_branch: f.branch, p_start: today, p_end: today, p_section: "deposits", p_mode: "payments" };
 let report = await call(cashier, "get_hospitality_workspace", reportArgs);
 assert.ok(report.finance.depositsHeld >= 30000); assert.ok(report.rows.some((r: { id: string }) => r.id === stayId)); ok("held deposits appear separately in payments reports");
 for (const db of [other, viewer, housekeeper]) assert.ok((await db.rpc("get_hospitality_workspace", reportArgs)).error); ok("deposit report cannot bypass financial access");
 const exported = await call(owner, "export_hospitality_workspace", { ...reportArgs, p_mode: undefined }); assert.ok(exported.rows.some((r: { id: string }) => r.id === stayId)); assert.equal(JSON.stringify(exported).includes("TEST-1234"), false); ok("deposit exports omit discount card numbers");
 await call(cashier, "set_invoice_external_receipt", { p_invoice: bill.id, p_receipt: "PAPER-002" });
 assert.equal(await call(cashier, "check_in_hospitality_cashier", arrival), stayId); ok("editing paper receipt does not break arrival retry");
 for (const db of [other, front, housekeeper]) assert.ok((await db.rpc("set_invoice_external_receipt", { p_invoice: bill.id, p_receipt: "bad" })).error); ok("receipt changes require finance write access");
 const checkout = { p_org: f.org, p_branch: f.branch, p_stay: stayId, p_acknowledge_debt: false, p_confirm_refund: true, p_refund_method: "cash", p_refund_reference: "RETURN-001" };
 assert.ok((await cashier.rpc("check_out_hospitality", { p_org: f.org, p_branch: f.branch, p_stay: stayId, p_acknowledge_debt: false })).error); ok("legacy checkout cannot abandon held deposit");
 assert.ok((await cashier.rpc("check_out_hospitality_with_deposit", { ...checkout, p_confirm_refund: false })).error); assert.ok((await front.rpc("check_out_hospitality_with_deposit", checkout)).error); ok("deposit return requires confirmation and collection permission");
 await call(cashier, "add_hospitality_charge", { p_org: f.org, p_branch: f.branch, p_stay: stayId, p_description: "Additional item", p_quantity: 1, p_unit_centavos: 1000, p_request: crypto.randomUUID() });
 assert.ok((await cashier.rpc("check_out_hospitality_with_deposit", checkout)).error);
 assert.equal((await owner.from("invoice_deposits").select("refunded_at").eq("invoice_id", bill.id).single()).data!.refunded_at, null); ok("failed debt acknowledgment rolls back deposit refund atomically");
 const paidCheckout = { ...checkout, p_acknowledge_debt: true };
 const checkoutRace = await Promise.all([cashier.rpc("check_out_hospitality_with_deposit", paidCheckout), owner.rpc("check_out_hospitality_with_deposit", paidCheckout)]); assert.equal(checkoutRace[0].error, null); assert.equal(checkoutRace[1].error, null);
 const returned = (await owner.from("invoice_deposits").select("*").eq("invoice_id", bill.id).single()).data!; assert.ok(returned.refunded_at);
 assert.equal((await owner.from("hospitality_room_availability").select("occupancy_status").eq("id", room).single()).data!.occupancy_status, "cleaning"); ok("concurrent checkout returns deposit once and sends room to cleaning");
 assert.ok((await cashier.rpc("check_out_hospitality_with_deposit", { ...paidCheckout, p_refund_reference: "changed" })).error); ok("changed refund replay rejected");
 assert.ok((await cashier.rpc("extend_hospitality_stay", { ...extension, p_expected_end: record.to_at, p_request: crypto.randomUUID() })).error); ok("checked-out stay cannot be extended");
 assert.equal(await call(cashier, "extend_hospitality_stay", replay), record.id); ok("exact extension retry after checkout is safe");
 report = await call(cashier, "get_hospitality_workspace", reportArgs); assert.equal(report.rows.find((r: { id: string }) => r.id === stayId).status, "Returned"); ok("deposit report records returned status");
 await call(housekeeper, "mark_hospitality_room_ready", { p_org: f.org, p_branch: f.branch, p_room: room, p_cleaning_stay: stayId });
 const free = { ...arrival, p_rates_version: 2, p_final: 0, p_discount_type: "manual", p_discount_card: "", p_deposit: 10000, p_tendered: 20000, p_receipt: "", p_request: crypto.randomUUID() };
 const freeStay = await call(cashier, "check_in_hospitality_cashier", free);
 const freeBill = (await owner.from("hospitality_stay_bills").select("invoice_id").eq("stay_id", freeStay).single()).data!.invoice_id;
 assert.equal((await owner.from("payments").select("id").eq("invoice_id", freeBill)).data!.length, 0); assert.equal((await owner.from("invoices").select("total_centavos,balance_centavos").eq("id", freeBill).single()).data!.total_centavos, 0); assert.equal((await owner.from("invoice_deposits").select("amount_centavos").eq("invoice_id", freeBill).single()).data!.amount_centavos, 10000); ok("complimentary room with refundable deposit creates no fake revenue payment");
 await call(cashier, "check_out_hospitality_with_deposit", { ...checkout, p_stay: freeStay });

 await call(housekeeper, "mark_hospitality_room_ready", { p_org: f.org, p_branch: f.branch, p_room: room, p_cleaning_stay: freeStay });
 const cardArrival = { ...arrival, p_rates_version: 2, p_method: "gcash", p_tendered: 110000, p_request: crypto.randomUUID() };
 const cardStay = await call(cashier, "check_in_hospitality_cashier", cardArrival);
 const cardBill = (await owner.from("hospitality_stay_bills").select("invoice_id").eq("stay_id", cardStay).single()).data!.invoice_id;
 const cardPayment = (await owner.from("payments").select("*").eq("invoice_id", cardBill).single()).data!;
 assert.equal(cardPayment.cash_tendered_centavos, null); assert.equal(cardPayment.cash_deposit_centavos, 0); assert.equal(cardPayment.amount_centavos, 80000); ok("noncash arrival splits exact total into room payment and deposit");
 await call(cashier, "reverse_payment", { p_payment_id: cardPayment.id, p_action: "refund", p_note: "Local regression" });
 assert.equal((await owner.from("invoice_deposits").select("refunded_at").eq("invoice_id", cardBill).single()).data!.refunded_at, null); ok("ordinary payment refund does not return the deposit");
 const collection = { p_invoice_id: cardBill, p_amount_centavos: 80000, p_method: "cash", p_request_key: crypto.randomUUID(), p_reference: "", p_notes: "", p_paid_date: null, p_currency: "PHP", p_receipt_number: "RECOLLECT-001" };
 const collected = await call(cashier, "record_invoice_collection_with_receipt", collection);
 assert.equal(await call(cashier, "record_invoice_collection_with_receipt", collection), collected);
 assert.ok((await cashier.rpc("record_invoice_collection_with_receipt", { ...collection, p_receipt_number: "changed" })).error); ok("receipted additional collection has exact idempotent retries");
 const legacyRates = rates.map(rate => ({ id: rate.id, label: rate.label, durationMinutes: rate.durationMinutes, priceCentavos: rate.priceCentavos }));
 const legacyRoom = await call(owner, "save_hospitality_room_with_rates", { ...roomArgs, p_name: `Legacy ${crypto.randomUUID().slice(0,8)}`, p_rates: legacyRates });
 const legacyArgs = { p_org: f.org, p_branch: f.branch, p_room: legacyRoom, p_rate: rates[0].id, p_rates_version: 1, p_tendered: 100000, p_method: "cash", p_reference: "", p_occupants: 1, p_guest_name: "", p_guest: null, p_notes: "", p_request: crypto.randomUUID() };
 const legacyStay = await call(cashier, "check_in_hospitality_paid", legacyArgs);
 const legacyEnd = (await owner.from("hospitality_stays").select("planned_checkout_at").eq("id", legacyStay).single()).data!.planned_checkout_at;
 const legacyExtension = { ...extension, p_stay: legacyStay, p_expected_end: legacyEnd, p_request: crypto.randomUUID(), p_rate: rates[0].id, p_rates_version: 1 };
 assert.ok((await cashier.rpc("extend_hospitality_stay", legacyExtension)).error); ok("legacy stay without an hourly price cannot invent an extension charge");
 await call(owner, "save_hospitality_room_with_rates", { ...roomArgs, p_room: legacyRoom, p_name: `Legacy ${legacyRoom.slice(0,8)}`, p_expected_version: 1 });
 assert.ok((await cashier.rpc("extend_hospitality_stay", legacyExtension)).error); ok("legacy rate selection rejects stale room version");
 await call(cashier, "extend_hospitality_stay", { ...legacyExtension, p_rates_version: 2 }); ok("legacy stay can explicitly select a newly configured hourly price");
 const annexRoom = await call(owner, "save_hospitality_room_with_rates", { ...roomArgs, p_branch: f.annex, p_name: `Annex ${crypto.randomUUID().slice(0,8)}` });
 const annexStay = await call(owner, "check_in_hospitality_cashier", { ...arrival, p_room: annexRoom, p_branch: f.annex, p_request: crypto.randomUUID() });
 const annexBill = (await owner.from("hospitality_stay_bills").select("invoice_id").eq("stay_id", annexStay).single()).data!.invoice_id;
 assert.equal((await cashier.from("invoice_deposits").select("*").eq("invoice_id", annexBill)).data!.length, 0);
 assert.ok((await cashier.rpc("check_out_hospitality_with_deposit", { ...checkout, p_stay: annexStay, p_branch: f.annex })).error); ok("assigned cashier cannot read or refund another branch deposit");
 console.log(`${passed} Hospitality pricing integration checks passed.`);
}
main().catch(error => { console.error(error); process.exitCode = 1; });
