import { randomUUID } from "node:crypto";
import Link from "next/link";
import { RecordTable } from "@/components/record-table";
import { ListTabs } from "@/components/list-tabs";
import { Plus, Search, X, ChevronLeft, ChevronRight } from "lucide-react";
import { z } from "zod";
import { zonedDateTimeToUtc } from "@/lib/operations";
import { Input } from "@/components/ui/input";
import { petContext } from "@/modules/pet-care/runtime";
import { groomingStatus } from "@/modules/pet-care/pets";
import { PageHeader } from "@/components/page-patterns";
import { FormMessage } from "@/components/form-message";
import { FormDialog } from "@/components/management-ui";
import { PetAppointmentForm } from "@/components/pet-care-forms";
import { Button } from "@/components/ui/button";
import { RecordLink } from "@/components/record-item";
export default async function Page({ searchParams }: { searchParams: Promise<{ dialog?: string; error?: string; q?: string; date?: string; status?: string; page?: string; customerId?: string }> }) {
 const [{ db, activeMembership, enabled, branchTimezone, openingHours }, query] = await Promise.all([petContext(), searchParams]);
 const search=(query.q??"").trim().slice(0,120);
 const date=z.iso.date().safeParse(query.date), page=Math.max(1,Math.min(100000,Number.parseInt(query.page??"1",10)||1));
 const statuses=["requested","confirmed","checked_in","in_service","completed","cancelled","no_show","ready","collected"];
 const status=statuses.includes(query.status??"")?query.status!:"";
 let appointmentQuery=db.from("appointments").select("id,customer_id,starts_at,status,appointment_services(service_name_snapshot),appointment_staff_assignments(organization_staff_profiles(full_name)),appointment_resource_assignments(scheduling_resources(name)),pet_appointment_details!inner(pet_name_snapshot,pickup_status)",{count:"exact"}).eq("organization_id",activeMembership.organizationId).eq("branch_id",activeMembership.branchId);
 if(search) appointmentQuery=appointmentQuery.ilike("pet_appointment_details.pet_name_snapshot",`%${search.replace(/[\\%_]/g,"\\$&")}%`);
 if(status) appointmentQuery=["ready","collected"].includes(status)?appointmentQuery.eq("pet_appointment_details.pickup_status",status):appointmentQuery.eq("status",status);
 if(date.success){const next=new Date(`${date.data}T12:00:00Z`);next.setUTCDate(next.getUTCDate()+1);appointmentQuery=appointmentQuery.gte("starts_at",zonedDateTimeToUtc(`${date.data}T00:00`,branchTimezone)!.toISOString()).lt("starts_at",zonedDateTimeToUtc(`${next.toISOString().slice(0,10)}T00:00`,branchTimezone)!.toISOString());}
 const pageHref=(number:number)=>`?${new URLSearchParams({q:search,date:date.success?date.data:"",status,page:String(number)})}`;
 const [appointments, pets, owners, services, staff, resources] = await Promise.all([
  appointmentQuery.order("starts_at", { ascending: false }).order("id").range((page-1)*50,page*50-1),
  db.from("pet_profiles").select("id,name,customer_id").eq("organization_id", activeMembership.organizationId).eq("is_active", true),
  db.from("customers").select("id,full_name").eq("organization_id", activeMembership.organizationId).eq("is_archived", false),
  db.from("services").select("id,name").eq("organization_id", activeMembership.organizationId).eq("is_active", true),
  db.from("organization_staff_profiles").select("id,full_name").eq("organization_id", activeMembership.organizationId).eq("is_active", true),
  db.from("scheduling_resources").select("id,name").eq("organization_id", activeMembership.organizationId).eq("branch_id", activeMembership.branchId).eq("is_active", true),
 ]);
 const canManage = enabled && ["owner","manager","advisor"].includes(activeMembership.role), ownerName = new Map((owners.data ?? []).map(owner => [owner.id, owner.full_name]));
 const related=(value:unknown,key:string)=>{const row=Array.isArray(value)?value[0]:value;return (row as Record<string,string>|null)?.[key]??"";};
 const assignmentLabel=(a:NonNullable<typeof appointments.data>[number])=>[a.appointment_staff_assignments.map(s=>related(s.organization_staff_profiles,"full_name")).join(", "),a.appointment_resource_assignments.map(r=>related(r.scheduling_resources,"name")).join(", ")].filter(Boolean).join(" · ");
 return <main id="pet-care-appointments" className="mx-auto min-w-0 max-w-6xl"><PageHeader id="pet-care-appointments-header" title="Grooming appointments" eyebrow={activeMembership.branchName} description="Pet, owner, and grooming progress in one place." action={canManage ? <div className="flex flex-wrap gap-2"><Button asChild variant="secondary"><Link id="pet-add-walk-in-button" href="/dashboard/pet-care/appointments?dialog=walk-in"><Plus size={16} aria-hidden="true"/>Add walk-in</Link></Button><Button id="pet-appointment-create-button" asChild><Link href="/dashboard/pet-care/appointments?dialog=create"><Plus size={16} aria-hidden="true"/>Book appointment</Link></Button></div> : undefined}/><FormMessage error={query.error ?? ([appointments,pets,owners,services,staff,resources].some(result => result.error) ? "Some appointment information could not be loaded." : undefined)}/>
 <ListTabs id="pet-appointment-tabs" baseHref="/dashboard/pet-care/appointments" query={query} value={status} options={[{value:"",label:"All"},{value:"checked_in",label:"Checked in"},{value:"confirmed",label:"Confirmed"},{value:"in_service",label:"Grooming"},{value:"ready",label:"Ready"},{value:"collected",label:"Collected"}]}/>
 <form id="pet-appointment-filters" className="mt-5 grid min-w-0 gap-4 rounded-ui-lg border border-admin-border bg-admin-surface p-4 shadow-ui-sm sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm">Search pet<Input id="pet-schedule-search" name="q" defaultValue={search} maxLength={120} className="mt-1"/></label><label className="text-sm">Date ({branchTimezone})<Input id="pet-schedule-date" name="date" type="date" defaultValue={date.success?date.data:""} className="mt-1"/></label><label className="text-sm">Progress<select id="pet-schedule-status" name="status" defaultValue={status} className="mt-1 min-h-11 w-full min-w-0 rounded-ui-md border border-admin-border bg-admin-surface px-3"><option value="">All progress</option>{statuses.map(v=><option key={v} value={v}>{groomingStatus(["ready","collected"].includes(v)?"completed":v,["ready","collected"].includes(v)?v:"not_ready")}</option>)}</select></label><div className="flex flex-wrap items-end justify-end gap-2"><Button id="pet-schedule-reset" asChild variant="secondary"><Link href="/dashboard/pet-care/appointments"><X size={16} aria-hidden="true"/>Reset</Link></Button><Button id="pet-schedule-filter" type="submit"><Search size={16} aria-hidden="true"/>Filter</Button></div></form>
 <div id="pet-appointment-list" className="mt-4"><RecordTable id="pet-appointments-table" caption="Grooming appointments" columns={[{key:"pet",label:"Pet / owner"},{key:"grooming",label:"Grooming",secondary:true},{key:"schedule",label:"Schedule",secondary:true},{key:"status",label:"Progress",align:"right"}]} rows={(appointments.data??[]).map(a=>({id:`pet-appointment-row-${a.id}`,cells:{
  pet:<><RecordLink id={`pet-appointment-link-${a.id}`} href={`/dashboard/pet-care/appointments/${a.id}`}>{related(a.pet_appointment_details,"pet_name_snapshot")}</RecordLink><p className="mt-1 text-xs text-admin-text-secondary">{ownerName.get(a.customer_id)??"Pet owner"}</p></>,grooming:<>{a.appointment_services.map(s=>s.service_name_snapshot).join(", ")}<p className="mt-1 text-xs text-admin-text-secondary">{assignmentLabel(a)}</p></>,schedule:new Intl.DateTimeFormat("en-PH",{timeZone:branchTimezone,dateStyle:"medium",timeStyle:"short"}).format(new Date(a.starts_at)),status:<span className="text-xs font-medium">{groomingStatus(a.status,related(a.pet_appointment_details,"pickup_status"))}</span>,
 },mobile:<><p>{a.appointment_services.map(s=>s.service_name_snapshot).join(", ")}</p><p>{assignmentLabel(a)}</p><p>{new Intl.DateTimeFormat("en-PH",{timeZone:branchTimezone,dateStyle:"medium",timeStyle:"short"}).format(new Date(a.starts_at))}</p></>}))}/></div>
 {!appointments.data?.length && !appointments.error ? <p className="mt-5 rounded-ui-lg border border-admin-border bg-admin-surface p-5 text-sm text-admin-text-secondary">No grooming appointments match these filters.</p> : null}
 <nav id="pet-schedule-pagination" aria-label="Appointment pages" className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm"><p>{appointments.count??0} appointments · Page {page}</p><div className="flex gap-2">{page>1?<Button asChild variant="secondary"><Link id="pet-schedule-previous" href={pageHref(page-1)}><ChevronLeft size={16} aria-hidden="true"/>Previous</Link></Button>:null}{page*50<(appointments.count??0)?<Button asChild variant="secondary"><Link id="pet-schedule-next" href={pageHref(page+1)}>Next<ChevronRight size={16} aria-hidden="true"/></Link></Button>:null}</div></nav>
 {canManage && ["create","walk-in"].includes(query.dialog??"") ? <FormDialog id="pet-appointment-dialog" title={query.dialog==="walk-in"?"Add grooming walk-in":"Book grooming appointment"} closeHref="/dashboard/pet-care/appointments"><PetAppointmentForm walkIn={query.dialog==="walk-in"} requestId={query.dialog==="walk-in"?randomUUID():undefined} owners={(owners.data??[]).map(owner=>({id:owner.id,name:owner.full_name}))} canCreateCatalog={["owner","manager"].includes(activeMembership.role)} timezone={branchTimezone} openingHours={openingHours} pets={(pets.data ?? []).filter(pet=>!query.customerId||pet.customer_id===query.customerId).map(pet => ({ id: pet.id, name: `${pet.name} · ${ownerName.get(pet.customer_id) ?? "Pet owner"}` }))} services={services.data ?? []} staff={(staff.data ?? []).map(s => ({ id: s.id, name: s.full_name }))} resources={resources.data ?? []}/></FormDialog> : null}</main>;
}
