import Link from "next/link";
import { notFound } from "next/navigation";
import { LogOut, Plus, CreditCard, Undo2, Printer, Clock, ReceiptText } from "lucide-react";
import { z } from "zod";
import { hospitalityContext, hospitalityShiftStaff } from "@/modules/hospitality/runtime";
import { billStatus, canHospitality, type Bill, type Stay, type Deposit, type RoomRate } from "@/modules/hospitality/contracts";
import { formatMoney } from "@/lib/operations";
import { paymentMethods } from "@/modules/core/payments/payment.service";
import { PageHeader } from "@/components/page-patterns";
import { Button } from "@/components/ui/button";
import { FormDialog } from "@/components/management-ui";
import { ListTabs } from "@/components/list-tabs";
import { RecordTable } from "@/components/record-table";
import { HospitalityActionForm } from "@/components/hospitality/action-form";
import { Field, fieldClass, SaveActions, dateLabel, LoadError, pageNumber, PageLinks } from "@/components/hospitality/shared";
import { addCharge, recordPayment, reverseStayPayment, saveReceipt } from "../../actions";

import { CheckOutForm } from "@/components/hospitality/check-out-form";
import { ExtensionForm } from "@/components/hospitality/extension-form";

type Query = { tab?: string; dialog?: string; payment?: string; page?: string };
export default async function StayPage({ params, searchParams }: { params: Promise<{ stayId: string }>; searchParams: Promise<Query> }) {
  const [{ stayId }, q, { db, activeMembership: m, user }] = await Promise.all([params, searchParams, hospitalityContext()]);
  if (!z.uuid().safeParse(stayId).success) notFound();
  const result = await db.from("hospitality_stays").select("*").eq("organization_id", m.organizationId).eq("id", stayId).maybeSingle();
  if (result.error) return <LoadError/>;
  if (!result.data) notFound();
  const stay = result.data as Stay, base = `/dashboard/hospitality/stays/${stay.id}`, finance = canHospitality(m.role, "financeRead"), sameBranch = m.branchId === stay.branch_id;
  const canWrite = sameBranch && canHospitality(m.role, "financeWrite"), operate = sameBranch && canHospitality(m.role, "operate");
  const branch = await db.from("branches").select("name,timezone").eq("id", stay.branch_id).single();
  const tz = branch.data?.timezone ?? m.timezone, page = pageNumber(q.page);
  let bill: Bill | null = null, financeError = false, debtAcknowledged = false;
  let deposit: Deposit | null = null;
  let rateSnapshot: { priceCentavos: number; finalCentavos?: number; discountType?: string; discountCard?: string; extensionHourlyCentavos?: number } | null = null;
  let arrival: { tendered: number; change: number } | null = null;
  if (finance) {
    const link = await db.from("hospitality_stay_bills").select("invoice_id,checkout_debt_acknowledged,rate_snapshot,check_in_request").eq("stay_id", stay.id).maybeSingle();
    financeError = Boolean(link.error);
    debtAcknowledged = link.data?.checkout_debt_acknowledged ?? false;
    rateSnapshot = link.data?.rate_snapshot ?? null;
    if (link.data?.check_in_request?.method === "cash" && link.data.rate_snapshot) arrival = { tendered: Number(link.data.check_in_request.tendered), change: Number(link.data.check_in_request.tendered) - Number(link.data.rate_snapshot.finalCentavos ?? link.data.rate_snapshot.priceCentavos) - Number(link.data.check_in_request.deposit ?? 0) };
    if (link.data) { const invoice = await db.from("invoices").select("id,invoice_number,status,total_centavos,paid_centavos,balance_centavos,customer_name_snapshot,external_receipt_number").eq("id", link.data.invoice_id).single(); bill = invoice.data as Bill | null; financeError ||= Boolean(invoice.error); }
  }
  if (bill) { const result = await db.from("invoice_deposits").select("amount_centavos,method,received_at,refunded_at,refund_method,refund_reference").eq("invoice_id", bill.id).maybeSingle(); deposit = result.data; financeError ||= Boolean(result.error); }
  const extensions = finance && bill ? await db.from("hospitality_stay_extensions").select("id,hours,from_at,to_at,base_centavos,final_centavos,discount_type,receipt_number,created_at", { count: "exact" }).eq("stay_id", stay.id).order("created_at", { ascending: false }).order("id").range((page - 1) * 50, page * 50 - 1) : { data: [], error: null, count: 0 };
  const extensionRoom = q.dialog === "extend" && canWrite ? await db.from("hospitality_rooms").select("rates,rates_version").eq("id", stay.room_id).single() : { data: null, error: null };
  financeError ||= Boolean(extensions.error || extensionRoom.error);
  const staffEvents = await db.from("hospitality_stay_staff_events").select("phase,cashier_name,housekeeper_name,recorded_at").eq("organization_id", m.organizationId).eq("stay_id", stay.id).order("recorded_at");
  let shiftStaff: Awaited<ReturnType<typeof hospitalityShiftStaff>> = [], staffError = false;
  if (q.dialog === "checkout" && operate) { try { shiftStaff = await hospitalityShiftStaff(m.organizationId, m.branchId); } catch { staffError = true; } }
  const [charges, payments] = bill && (q.tab === "charges" || q.dialog) ? await Promise.all([
    db.from("invoice_items").select("id,description_snapshot,quantity,unit_price_centavos,line_total_centavos", { count: "exact" }).eq("invoice_id", bill.id).order("id").range((page - 1) * 50, page * 50 - 1),
    db.from("payments").select("id,amount_centavos,method,status,reference,paid_at,receipt_number", { count: "exact" }).eq("invoice_id", bill.id).order("paid_at", { ascending: false }).range((page - 1) * 50, page * 50 - 1),
  ]) : [{ data: [], error: null, count: 0 }, { data: [], error: null, count: 0 }];
  const payment = payments.data?.find(p => p.id === q.payment);
  const tab = q.tab === "charges" && finance ? "charges" : q.tab === "history" ? "history" : "overview";
  return <main id="hospitality-stay-details" className="mx-auto min-w-0 max-w-6xl">
    <PageHeader id="hospitality-stay-header" eyebrow={`${branch.data?.name ?? m.branchName} · ${stay.checked_out_at ? "Checked out" : "In house"}`} title={stay.room_name_snapshot} description={`Checked in ${dateLabel(stay.checked_in_at, tz)} · ${stay.occupants} occupant${stay.occupants === 1 ? "" : "s"}`} action={operate && !stay.checked_out_at ? <Button id="hospitality-check-out-button" asChild variant="secondary"><Link href={`${base}?dialog=checkout`}><LogOut size={16}/>Check out</Link></Button> : undefined}/>
    {!sameBranch ? <p className="mt-3 rounded-xl bg-slate-100 p-3 text-sm">Viewing another accessible branch. Switch to {branch.data?.name ?? "that branch"} to record changes.</p> : null}
    {stay.planned_checkout_at || (canWrite && bill && !stay.checked_out_at) ? <section id="hospitality-stay-period" className="mt-3 rounded-xl border border-admin-border bg-white p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><p>{stay.planned_checkout_at ? `${stay.stay_period_label ?? "Stay"} · Paid period ends ${dateLabel(stay.planned_checkout_at, tz)}` : "No paid end time recorded for this stay."}</p>{canWrite && !stay.checked_out_at && !financeError ? <Button asChild variant="secondary" size="sm"><Link id="hospitality-extend-button" href={`${base}?dialog=extend`}><Clock size={16}/>Extend stay</Link></Button> : null}</div>{!stay.checked_out_at ? <p className="mt-1 text-xs text-slate-500">The room remains occupied until you mark it checked out.</p> : null}</section> : null}
    {finance ? financeError ? <LoadError>Financial information could not be loaded. Refresh before making changes.</LoadError> : <section id="hospitality-stay-payment-summary" className="mt-4 grid grid-cols-2 gap-3 rounded-xl border border-admin-border bg-white p-4 shadow-sm sm:grid-cols-4"><Summary label="Financial status" value={billStatus(bill)}/><Summary label="Total charges" value={formatMoney(bill?.total_centavos ?? 0, m.currency)}/><Summary label="Paid" value={formatMoney(bill?.paid_centavos ?? 0, m.currency)}/><Summary label="Balance" value={formatMoney(bill?.balance_centavos ?? 0, m.currency)}/></section> : null}
    {deposit && !financeError ? <section id="hospitality-deposit-summary" className="mt-3 rounded-xl border border-admin-border bg-white p-4"><Summary label={deposit.refunded_at ? "Deposit returned" : "Refundable deposit held"} value={formatMoney(deposit.amount_centavos, m.currency)}/><p className="mt-1 text-xs text-slate-500">{deposit.refunded_at ? `Returned ${dateLabel(deposit.refunded_at, tz)} via ${deposit.refund_method?.replaceAll("_", " ")}.` : "Separate from room charges. Return this amount to the guest at checkout."}</p></section> : null}
    <details id="hospitality-stay-check-in-details" className="mt-3 rounded-xl border border-admin-border bg-white p-4"><summary className="cursor-pointer text-sm font-medium">Check-in details & staff history</summary>
    {arrival ? <section id="hospitality-arrival-cash-summary" className="mt-3 grid grid-cols-2 gap-4 rounded-xl border border-brand-border bg-brand-tint p-4"><Summary label="Cash received at check-in" value={formatMoney(arrival.tendered, m.currency)}/><Summary label="Change returned" value={formatMoney(arrival.change, m.currency)}/></section> : null}
    {finance && rateSnapshot && !financeError ? <section id="hospitality-agreed-price" className="mt-3 grid grid-cols-2 gap-4 rounded-xl border border-admin-border bg-white p-4"><Summary label="Original room rate" value={formatMoney(rateSnapshot.priceCentavos, m.currency)}/><Summary label="Final room price" value={formatMoney(rateSnapshot.finalCentavos ?? rateSnapshot.priceCentavos, m.currency)}/>{rateSnapshot.discountType && rateSnapshot.discountType !== "none" ? <p className="col-span-2 text-sm capitalize">Discount: {rateSnapshot.discountType}{rateSnapshot.discountCard ? ` · Card ending ${rateSnapshot.discountCard.slice(-4)}` : ""}</p> : null}</section> : null}
    {staffEvents.error ? <LoadError>Shift history could not be loaded.</LoadError> : <section id="hospitality-stay-shift-history" className="mt-3 rounded-xl border border-admin-border bg-white p-4"><h2 className="text-sm font-medium">Staff by shift</h2>{staffEvents.data?.length ? <div className="mt-3 grid gap-4 sm:grid-cols-2">{staffEvents.data.map(event => <div key={event.phase} className="min-w-0 text-sm"><p className="font-medium">{event.phase === "check_in" ? "Check-in" : "Checkout"}</p><p className="mt-1 break-words">Cashier: {event.cashier_name}</p><p className="break-words">Housekeeper: {event.housekeeper_name}</p><p className="mt-1 text-xs text-slate-500">{dateLabel(event.recorded_at, tz)}</p></div>)}</div> : <p className="mt-2 text-sm text-slate-500">No shift staff were recorded for this earlier stay.</p>}</section>}
    </details>
    <ListTabs id="hospitality-stay-tabs" baseHref={base} parameter="tab" value={tab} query={{}} options={[{ value: "overview", label: "Overview" }, ...(finance ? [{ value: "charges", label: "Charges & payments" }] : []), { value: "history", label: "History" }]}/>
    {tab === "overview" ? <section className="mt-4 rounded-xl border border-admin-border bg-white p-5 shadow-sm"><h2 className="text-lg">Stay information</h2><p className="mt-3 text-sm">Guest: {stay.guest_id ? <Link className="text-brand-primary underline" href={`/dashboard/customers/${stay.guest_id}`}>{stay.guest_name_snapshot}</Link> : stay.guest_name_snapshot === "Walk-in" ? "No name recorded" : stay.guest_name_snapshot}</p><p className="mt-2 whitespace-pre-wrap text-sm">{stay.notes || "No stay notes."}</p>{stay.checked_out_at ? <p className="mt-3 text-sm">Checked out {dateLabel(stay.checked_out_at, tz)}. Check Rooms for current cleaning status and availability. Financial records remain available for later collection.</p> : null}<p className="mt-3 text-xs text-slate-500">Room and guest names above are preserved from check-in.</p></section> : null}
    {tab === "history" ? <section className="mt-4 rounded-xl border border-admin-border bg-white p-5 shadow-sm"><h2 className="text-lg">Occupancy history</h2><ol className="mt-3 space-y-3 text-sm"><li>Checked in · {dateLabel(stay.checked_in_at, tz)}</li><li>{stay.checked_out_at ? `Checked out · ${dateLabel(stay.checked_out_at, tz)}` : "Currently in house"}</li>{finance && debtAcknowledged ? <li>Outstanding balance acknowledged at checkout; bill preserved.</li> : null}</ol></section> : null}
    {tab === "charges" && !financeError ? <section id="hospitality-stay-charges" className="mt-4 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg">Charges & payments</h2><div className="flex flex-wrap justify-end gap-2">{canWrite && bill?.status !== "void" ? <Button id="hospitality-add-charge-button" asChild variant="secondary"><Link href={`${base}?tab=charges&dialog=charge`}><Plus size={16}/>Additional charge</Link></Button> : null}{canWrite && bill && bill.balance_centavos > 0 ? <Button id="hospitality-record-payment-button" asChild><Link href={`${base}?tab=charges&dialog=payment`}><CreditCard size={16}/>Record payment</Link></Button> : null}{bill ? <Button asChild variant="secondary"><Link id="hospitality-receipt-link" href={`${base}/receipt`}><Printer size={16}/>Statement</Link></Button> : null}</div></div>
      <p className="text-xs text-slate-500">Charges use the agreed final prices. Refundable deposits are separate from room revenue and do not pay down the bill. Additional charges do not deduct inventory. Recorded payments document money received by the business; NegOSu does not process the transaction.</p>
      {bill ? <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-admin-border bg-white p-4"><p className="min-w-0 break-words text-sm">Paper receipt: {bill.external_receipt_number || "Not recorded"}</p>{canWrite ? <Button asChild variant="secondary" size="sm"><Link id="hospitality-edit-receipt-button" href={`${base}?tab=charges&dialog=receipt`}><ReceiptText size={16}/>Edit receipt number</Link></Button> : null}</div> : null}
      {(extensions.data ?? []).length ? <RecordTable id="hospitality-extension-table" caption="Stay extensions" columns={[{ key: "period", label: "Extension" }, { key: "price", label: "Final price", align: "right" }]} rows={(extensions.data ?? []).map(e => ({ id: `hospitality-extension-${e.id}`, cells: { period: <>{e.hours} hour(s) · Ends {dateLabel(e.to_at, tz)}<p className="text-xs text-slate-500">Original {formatMoney(e.base_centavos, m.currency)} · {e.discount_type === "none" ? "No discount" : e.discount_type}{e.receipt_number ? ` · Receipt ${e.receipt_number}` : ""}</p></>, price: formatMoney(e.final_centavos, m.currency) } }))}/> : null}
      {charges.error || payments.error ? <LoadError/> : <><RecordTable id="hospitality-charge-table" caption="Agreed charges" columns={[{ key: "description", label: "Charge" }, { key: "quantity", label: "Quantity", secondary: true }, { key: "unit", label: "Unit amount", secondary: true }, { key: "total", label: "Total", align: "right" }]} rows={(charges.data ?? []).map(c => ({ id: `hospitality-charge-${c.id}`, cells: { description: c.description_snapshot, quantity: c.quantity, unit: formatMoney(c.unit_price_centavos, m.currency), total: formatMoney(c.line_total_centavos, m.currency) }, mobile: <p>{c.quantity} × {formatMoney(c.unit_price_centavos, m.currency)}</p> }))} empty="No charges recorded. Add the agreed accommodation charge when known."/>
      <RecordTable id="hospitality-payment-table" caption="Recorded guest payments" columns={[{ key: "payment", label: "Payment" }, { key: "date", label: "Received", secondary: true }, { key: "amount", label: "Amount", align: "right" }, { key: "action", label: "", className: "w-16" }]} rows={(payments.data ?? []).map(p => ({ id: `hospitality-payment-${p.id}`, cells: { payment: <><p className="capitalize">{p.method.replaceAll("_", " ")} · {p.status}</p><p className="text-xs text-slate-500">{p.reference || "No reference"}{p.receipt_number ? ` · Receipt ${p.receipt_number}` : ""}</p></>, date: dateLabel(p.paid_at, tz), amount: formatMoney(p.amount_centavos, m.currency), action: canWrite && p.status === "paid" ? <Button asChild variant="secondary" size="sm"><Link href={`${base}?tab=charges&dialog=reverse&payment=${p.id}&page=${page}`} aria-label="Reverse payment"><Undo2 size={16}/></Link></Button> : null }, mobile: <p>{dateLabel(p.paid_at, tz)}</p> }))}/><PageLinks page={page} count={Math.max(charges.count ?? 0, payments.count ?? 0, extensions.count ?? 0)} href={p => `${base}?tab=charges&page=${p}`}/></>}
    </section> : null}
    {q.dialog === "checkout" && operate && !stay.checked_out_at && !financeError ? <FormDialog id="hospitality-check-out-dialog" title={`Check out · ${stay.room_name_snapshot}`} closeHref={base} size="md"><CheckOutForm stayId={stay.id} roomName={stay.room_name_snapshot} balance={bill?.balance_centavos ?? null} deposit={deposit} currency={m.currency} canWrite={canWrite} canManageStaff={m.role === "owner"} staff={shiftStaff} staffError={staffError} staffScope={{ userId: user.id, organizationId: m.organizationId, branchId: m.branchId }} closeHref={base}/></FormDialog> : null}
    {q.dialog === "charge" && canWrite && !financeError ? <FormDialog id="hospitality-charge-dialog" title="Add additional charge" closeHref={`${base}?tab=charges`} size="md"><HospitalityActionForm id="hospitality-charge-form" action={addCharge}><input type="hidden" name="stayId" value={stay.id}/><input type="hidden" name="requestKey" value={crypto.randomUUID()}/><Field label="Description *" full><input id="hospitality-charge-description" name="description" required maxLength={200} defaultValue={!bill ? "Accommodation" : ""} className={fieldClass}/></Field><Field label="Quantity *"><input id="hospitality-charge-quantity" name="quantity" required type="number" min={1} max={1000} defaultValue={1} className={fieldClass}/></Field><Field label={`Unit amount (${m.currency}) *`}><input id="hospitality-charge-amount" name="amount" required inputMode="decimal" className={fieldClass}/></Field><SaveActions id="hospitality-charge" label="Save charge" closeHref={base}/></HospitalityActionForm></FormDialog> : null}
    {q.dialog === "payment" && canWrite && bill && bill.balance_centavos > 0 ? <FormDialog id="hospitality-payment-dialog" title="Record guest payment" description={`Remaining balance: ${formatMoney(bill.balance_centavos, m.currency)}. Record only money already received.`} closeHref={`${base}?tab=charges`} size="md"><HospitalityActionForm id="hospitality-payment-form" action={recordPayment}><input type="hidden" name="stayId" value={stay.id}/><input type="hidden" name="requestKey" value={crypto.randomUUID()}/><Field label={`Amount (${m.currency}) *`}><input id="hospitality-payment-amount" name="amount" required inputMode="decimal" defaultValue={(bill.balance_centavos / 100).toFixed(2)} className={fieldClass}/></Field><Field label="Method *"><select id="hospitality-payment-method" name="method" className={fieldClass}>{paymentMethods.map(method => <option key={method} value={method}>{method.replaceAll("_", " ")}</option>)}</select></Field><Field label="Date received *"><input id="hospitality-payment-date" name="paidDate" type="date" required defaultValue={new Intl.DateTimeFormat("en-CA", { timeZone: tz }).format(new Date())} className={fieldClass}/></Field><Field label="Reference"><input id="hospitality-payment-reference" name="reference" maxLength={200} className={fieldClass}/></Field><Field label="Receipt number (optional)"><input id="hospitality-payment-receipt-number" name="receiptNumber" maxLength={80} className={fieldClass}/></Field><Field label="Notes" full><textarea id="hospitality-payment-notes" name="notes" maxLength={2000} className={fieldClass}/></Field><SaveActions id="hospitality-payment" label="Record payment" closeHref={base}/></HospitalityActionForm></FormDialog> : null}
    {q.dialog === "receipt" && canWrite && bill && !financeError ? <FormDialog id="hospitality-receipt-dialog" title="Paper receipt number" closeHref={`${base}?tab=charges`} size="md"><HospitalityActionForm id="hospitality-receipt-form" action={saveReceipt}><input type="hidden" name="stayId" value={stay.id}/><Field label="Receipt number (optional)" full><input id="hospitality-stay-receipt-number" name="receiptNumber" defaultValue={bill.external_receipt_number ?? ""} maxLength={80} className={fieldClass}/></Field><SaveActions id="hospitality-receipt" label="Save receipt number" closeHref={`${base}?tab=charges`}/></HospitalityActionForm></FormDialog> : null}
    {q.dialog === "extend" && canWrite && !stay.checked_out_at && !financeError && extensionRoom.data ? <FormDialog id="hospitality-extension-dialog" title="Extend stay" closeHref={base}><ExtensionForm stayId={stay.id} expectedEnd={stay.planned_checkout_at} rates={extensionRoom.data.rates as RoomRate[]} version={extensionRoom.data.rates_version} snapshotHourly={rateSnapshot?.extensionHourlyCentavos ?? 0} currency={m.currency} requestKey={crypto.randomUUID()} closeHref={base}/></FormDialog> : null}
    {q.dialog === "reverse" && canWrite && payment?.status === "paid" ? <FormDialog id="hospitality-payment-reversal-dialog" title="Reverse recorded payment" description="This updates the ledger only. Arrange any actual refund separately." closeHref={`${base}?tab=charges`} size="md"><HospitalityActionForm id="hospitality-reversal-form" action={reverseStayPayment}><input type="hidden" name="stayId" value={stay.id}/><input type="hidden" name="paymentId" value={payment.id}/><Field label="Reversal"><select id="hospitality-reversal-kind" name="reversal" className={fieldClass}><option value="void">Void incorrect entry</option><option value="refund">Record refund</option></select></Field><Field label="Reason *"><input id="hospitality-reversal-reason" name="reason" required minLength={3} maxLength={500} className={fieldClass}/></Field><SaveActions id="hospitality-reversal" label="Confirm reversal" closeHref={base}/></HospitalityActionForm></FormDialog> : null}
  </main>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-base [overflow-wrap:anywhere]">{value}</p></div>; }
