-- Deposits are separate liabilities, never included in accommodation collections.
create or replace function public.get_hospitality_workspace(p_org uuid,p_branch uuid,p_start date,p_end date,p_section text default 'stays',p_page integer default 1,p_mode text default 'report') returns jsonb
language plpgsql stable security definer set search_path=public,pg_temp as $$
declare finance boolean; inventory_access boolean; result jsonb; details jsonb; total_rows bigint; branch_ids uuid[]; offset_rows integer; financial jsonb;
begin
 if not public.hospitality_enabled(p_org) or not public.is_org_member(p_org) then raise exception 'Hospitality access denied' using errcode='42501'; end if;
 if p_mode not in('report','overview','payments','history') or p_section not in('stays','collections','outstanding','deposits','rooms','inventory','movements') or p_page is null or p_page not between 1 and 100000 or p_start is null or p_end is null or p_end<p_start or p_end-p_start>731 then raise exception 'Invalid report filters' using errcode='22023'; end if;
 if (p_mode in('overview','history') and p_section<>'stays') or (p_mode='payments' and p_section not in('stays','collections','outstanding','deposits')) then raise exception 'Invalid workspace section' using errcode='22023'; end if;
 if p_mode='report' then perform public.authorize_report_scope(p_org,p_start,p_end,p_branch,false); end if;
 finance:=p_mode<>'history' and public.has_org_role(p_org,array['owner','manager','advisor','cashier']::public.organization_role[]);
 inventory_access:=p_mode in('report','overview') and public.has_permission(p_org,'inventory.manage');
 if (p_mode='payments' or p_section in('collections','outstanding','deposits')) and not finance then raise exception 'Finance access required' using errcode='42501'; end if;
 if p_section in('inventory','movements') and not inventory_access then raise exception 'Inventory access required' using errcode='42501'; end if;
 if p_branch is not null and not exists(select 1 from public.branches where id=p_branch and organization_id=p_org and public.can_access_branch(p_org,id)) then raise exception 'Branch not found' using errcode='42501'; end if;
 select coalesce(array_agg(id),'{}') into branch_ids from public.branches where organization_id=p_org and (p_branch is null or id=p_branch) and public.can_access_branch(p_org,id);
 offset_rows:=(p_page-1)*50;
 select jsonb_build_object('occupied',count(*) filter(where is_active and exists(select 1 from public.hospitality_stays s where s.room_id=r.id and s.checked_out_at is null)),
 'cleaning',count(*) filter(where is_active and cleaning_required),
 'vacant',count(*) filter(where is_active and not cleaning_required and not exists(select 1 from public.hospitality_stays s where s.room_id=r.id and s.checked_out_at is null)),
 'inactive',count(*) filter(where not is_active)) into result from public.hospitality_rooms r where branch_id=any(branch_ids);
 select result||jsonb_build_object('checkIns',count(*) filter(where s.checked_in_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and s.checked_in_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone),
 'checkOuts',count(*) filter(where s.checked_out_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and s.checked_out_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone),
 'inHouse',count(*) filter(where s.checked_out_at is null)) into result from public.hospitality_stays s join public.branches b on b.id=s.branch_id where s.branch_id=any(branch_ids);
 if finance then
 select jsonb_build_object('charges',coalesce(sum(i.total_centavos),0),'paid',coalesce(sum(i.paid_centavos),0),'outstanding',coalesce(sum(i.balance_centavos),0),
 'checkedOutDebt',count(*) filter(where s.checked_out_at is not null and i.balance_centavos>0)) into financial
 from public.hospitality_stay_bills sb join public.invoices i on i.id=sb.invoice_id join public.hospitality_stays s on s.id=sb.stay_id where sb.branch_id=any(branch_ids) and i.status<>'void';
 select financial||jsonb_build_object('collected',coalesce(sum(p.amount_centavos),0)) into financial from public.payments p join public.hospitality_stay_bills sb on sb.invoice_id=p.invoice_id join public.branches b on b.id=p.branch_id
 where p.branch_id=any(branch_ids) and p.status='paid' and p.paid_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and p.paid_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone;
 select financial||jsonb_build_object('methods',coalesce(jsonb_agg(to_jsonb(x)),'[]')) into financial from (select p.method,sum(p.amount_centavos) amount from public.payments p join public.hospitality_stay_bills sb on sb.invoice_id=p.invoice_id join public.branches b on b.id=p.branch_id where p.branch_id=any(branch_ids) and p.status='paid' and p.paid_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and p.paid_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone group by p.method)x;
 select financial||jsonb_build_object('depositsHeld',coalesce(sum(d.amount_centavos) filter(where d.refunded_at is null),0),
 'depositsReceived',coalesce(sum(d.amount_centavos) filter(where (d.received_at at time zone b.timezone)::date between p_start and p_end),0),
 'depositsReturned',coalesce(sum(d.amount_centavos) filter(where (d.refunded_at at time zone b.timezone)::date between p_start and p_end),0)) into financial
 from public.invoice_deposits d join public.hospitality_stay_bills sb on sb.invoice_id=d.invoice_id join public.branches b on b.id=d.branch_id where d.branch_id=any(branch_ids);
 result:=result||jsonb_build_object('finance',financial);
 end if;
 if inventory_access then
 select result||jsonb_build_object('lowStock',count(*) filter(where low_stock),'stockItems',count(*)) into result from public.inventory_stock where branch_id=any(branch_ids) and is_active;
 end if;
 if p_section='stays' then
 select count(*) into total_rows from public.hospitality_stays s join public.branches b on b.id=s.branch_id where s.branch_id=any(branch_ids) and (s.checked_out_at is null or s.checked_in_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and s.checked_in_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone or s.checked_out_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and s.checked_out_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone);
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into details from (select s.id,s.branch_id,b.timezone,s.guest_name_snapshot guest,s.room_name_snapshot room,s.occupants,s.checked_in_at,s.checked_out_at,b.name branch from public.hospitality_stays s join public.branches b on b.id=s.branch_id where s.branch_id=any(branch_ids) and (s.checked_out_at is null or s.checked_in_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and s.checked_in_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone or s.checked_out_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and s.checked_out_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone) order by (s.checked_out_at is null) desc,s.checked_in_at desc,s.id limit 50 offset offset_rows)x;
 elsif p_section='outstanding' then
 select count(*) into total_rows from public.hospitality_stay_bills sb join public.invoices i on i.id=sb.invoice_id where sb.branch_id=any(branch_ids) and i.balance_centavos>0 and i.status<>'void';
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into details from(select s.id,b.name branch,s.guest_name_snapshot guest,s.room_name_snapshot room,s.checked_out_at,i.total_centavos charges,i.paid_centavos paid,i.balance_centavos balance from public.hospitality_stay_bills sb join public.invoices i on i.id=sb.invoice_id join public.hospitality_stays s on s.id=sb.stay_id join public.branches b on b.id=s.branch_id where sb.branch_id=any(branch_ids) and i.balance_centavos>0 and i.status<>'void' order by i.balance_centavos desc,s.id limit 50 offset offset_rows)x;
 elsif p_section='deposits' then
 select count(*) into total_rows from public.invoice_deposits d join public.hospitality_stay_bills sb on sb.invoice_id=d.invoice_id join public.branches b on b.id=d.branch_id where d.branch_id=any(branch_ids) and (d.refunded_at is null or (d.received_at at time zone b.timezone)::date between p_start and p_end or (d.refunded_at at time zone b.timezone)::date between p_start and p_end);
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into details from(select s.id,d.id deposit_id,b.name branch,b.timezone,s.room_name_snapshot room,d.amount_centavos amount,d.method,d.received_at,d.refunded_at,case when d.refunded_at is null then 'Held' else 'Returned' end status from public.invoice_deposits d join public.hospitality_stay_bills sb on sb.invoice_id=d.invoice_id join public.hospitality_stays s on s.id=sb.stay_id join public.branches b on b.id=d.branch_id where d.branch_id=any(branch_ids) and (d.refunded_at is null or (d.received_at at time zone b.timezone)::date between p_start and p_end or (d.refunded_at at time zone b.timezone)::date between p_start and p_end) order by (d.refunded_at is null) desc,d.received_at desc,d.id limit 50 offset offset_rows)x;
 elsif p_section='collections' then
 select count(*) into total_rows from public.payments p join public.hospitality_stay_bills sb on sb.invoice_id=p.invoice_id join public.branches b on b.id=p.branch_id where p.branch_id=any(branch_ids) and p.paid_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and p.paid_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone;
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into details from(select s.id,b.name branch,b.timezone,p.id payment_id,s.guest_name_snapshot guest,s.room_name_snapshot room,p.amount_centavos amount,p.method,p.status,p.reference,p.receipt_number,p.paid_at from public.payments p join public.hospitality_stay_bills sb on sb.invoice_id=p.invoice_id join public.hospitality_stays s on s.id=sb.stay_id join public.branches b on b.id=p.branch_id where p.branch_id=any(branch_ids) and p.paid_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and p.paid_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone order by p.paid_at desc,p.id limit 50 offset offset_rows)x;
 elsif p_section='rooms' then
 select count(*) into total_rows from public.hospitality_rooms where branch_id=any(branch_ids);
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into details from(select r.id,r.name room,r.room_type,r.capacity,b.name branch,case when not r.is_active then 'Inactive' when s.id is not null then 'Occupied' when r.cleaning_required then 'Cleaning' else 'Vacant' end status,s.id stay_id,s.guest_name_snapshot guest from public.hospitality_rooms r join public.branches b on b.id=r.branch_id left join public.hospitality_stays s on s.room_id=r.id and s.checked_out_at is null where r.branch_id=any(branch_ids) order by r.name,r.id limit 50 offset offset_rows)x;
 elsif p_section='inventory' then
 select count(*) into total_rows from public.inventory_stock where branch_id=any(branch_ids) and is_active;
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into details from(select stock.id,stock.name,stock.unit,stock.quantity_on_hand,stock.reorder_level,stock.low_stock,b.name branch from public.inventory_stock stock join public.branches b on b.id=stock.branch_id where stock.branch_id=any(branch_ids) and stock.is_active order by stock.name,stock.id limit 50 offset offset_rows)x;
 elsif p_section='movements' then
 select count(*) into total_rows from public.inventory_movements m join public.branches b on b.id=m.branch_id where m.branch_id=any(branch_ids) and m.created_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and m.created_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone;
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into details from(select m.id,b.name branch,b.timezone,i.name,m.movement_type,m.quantity_delta,m.created_at from public.inventory_movements m join public.inventory_items i on i.id=m.inventory_item_id join public.branches b on b.id=m.branch_id where m.branch_id=any(branch_ids) and m.created_at>=(case when p_mode='overview' then (now() at time zone b.timezone)::date else p_start end)::timestamp at time zone b.timezone and m.created_at<((case when p_mode='overview' then (now() at time zone b.timezone)::date else p_end end)+1)::timestamp at time zone b.timezone order by m.created_at desc,m.id limit 50 offset offset_rows)x;
 end if;
 return result||jsonb_build_object('rows',details,'rowCount',total_rows,'page',p_page);
end $$;
revoke all on function public.get_hospitality_workspace(uuid,uuid,date,date,text,integer,text) from public,anon;
grant execute on function public.get_hospitality_workspace(uuid,uuid,date,date,text,integer,text) to authenticated;

